-- liquibase formatted sql

-- changeset codex:001
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "roles" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role_name" VARCHAR(255) NOT NULL UNIQUE,
    "status" BIGINT
);

-- changeset codex:002
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_name" VARCHAR(255) NOT NULL UNIQUE,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password_hash" VARCHAR(255) NOT NULL,
    "status" BIGINT NOT NULL,
    "roles_id" BIGINT NOT NULL,
    CONSTRAINT "fk_users_roles" FOREIGN KEY ("roles_id") REFERENCES "roles" ("id")
);

-- changeset codex:003
-- validCheckSum: ANY
INSERT INTO "roles" ("role_name", "status")
VALUES
    ('ADMIN', 2),
    ('MOTHER', 2),
    ('FARTHER', 2)
ON CONFLICT ("role_name") DO NOTHING;

-- changeset codex:004
-- validCheckSum: ANY
INSERT INTO "users" ("user_name", "email", "password_hash", "status", "roles_id")
SELECT 'admin', 'admin@babyoi.local', '$2a$10$Sp5KC4ogUQfX2l/he1tjwORGszx9WrBL.q8oBcF0mz34VG/PLZ2ju', 2, r."id"
FROM "roles" r
WHERE r."role_name" = 'ADMIN'
ON CONFLICT ("email") DO NOTHING;

-- changeset codex:005
-- validCheckSum: ANY
INSERT INTO "users" ("user_name", "email", "password_hash", "status", "roles_id")
SELECT 'mother', 'mother@babyoi.local', '$2a$10$Sp5KC4ogUQfX2l/he1tjwORGszx9WrBL.q8oBcF0mz34VG/PLZ2ju', 2, r."id"
FROM "roles" r
WHERE r."role_name" = 'MOTHER'
ON CONFLICT ("email") DO NOTHING;

-- changeset codex:006
-- validCheckSum: ANY
INSERT INTO "users" ("user_name", "email", "password_hash", "status", "roles_id")
SELECT 'farther', 'farther@babyoi.local', '$2a$10$Sp5KC4ogUQfX2l/he1tjwORGszx9WrBL.q8oBcF0mz34VG/PLZ2ju', 2, r."id"
FROM "roles" r
WHERE r."role_name" = 'FARTHER'
ON CONFLICT ("email") DO NOTHING;

-- changeset codex:007
CREATE TABLE IF NOT EXISTS "user_session_token" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "token_hash" VARCHAR(128) NOT NULL UNIQUE,
    "user_id" BIGINT NOT NULL,
    "issued_at" TIMESTAMP(6) NOT NULL,
    "last_used_at" TIMESTAMP(6) NOT NULL,
    "expires_at" TIMESTAMP(6) NOT NULL,
    CONSTRAINT "fk_user_session_token_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id")
);

-- changeset codex:008
CREATE INDEX IF NOT EXISTS "idx_user_session_token_expires_at"
    ON "user_session_token" ("expires_at");
