-- liquibase formatted sql

-- changeset codex:009
CREATE TABLE IF NOT EXISTS "food_library" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "function_code" BIGINT,
    "name" VARCHAR(255),
    "advance_for" VARCHAR(100),
    "created_at" TIMESTAMP(6),
    "updated_at" TIMESTAMP(6),
    "created_by" VARCHAR(255),
    "updated_by" VARCHAR(255),
    "status" BIGINT
);

-- changeset codex:010
CREATE TABLE IF NOT EXISTS "food_ingredients" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name_ingredients" VARCHAR(255),
    "created_at" TIMESTAMP(6),
    "created_by" VARCHAR(255),
    "updated_by" VARCHAR(255),
    "updated_at" TIMESTAMP(6),
    "status" BIGINT
);

-- changeset codex:011
CREATE TABLE IF NOT EXISTS "food_library_ingredients" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "food_lib_id" BIGINT,
    "food_ing_id" BIGINT,
    "amount_per_serving" DOUBLE PRECISION,
    "unit" VARCHAR(255),
    "status" BIGINT,
    "description" TEXT,
    CONSTRAINT "fk_food_library_ingredients_food_library"
        FOREIGN KEY ("food_lib_id") REFERENCES "food_library" ("id"),
    CONSTRAINT "fk_food_library_ingredients_food_ingredients"
        FOREIGN KEY ("food_ing_id") REFERENCES "food_ingredients" ("id")
);

-- changeset codex:012
CREATE TABLE IF NOT EXISTS "ingredient_nutrition" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "food_ingredient_id" BIGINT,
    "base_amount" DOUBLE PRECISION,
    "base_unit" VARCHAR(255),
    "calories" DOUBLE PRECISION DEFAULT 0,
    "calories_unit" VARCHAR(255),
    "protein" DOUBLE PRECISION DEFAULT 0,
    "protein_unit" VARCHAR(255),
    "carbs" DOUBLE PRECISION DEFAULT 0,
    "carbs_unit" VARCHAR(255),
    "fat" DOUBLE PRECISION DEFAULT 0,
    "fat_unit" VARCHAR(255),
    "fiber" DOUBLE PRECISION DEFAULT 0,
    "fiber_unit" VARCHAR(255),
    "sugar" DOUBLE PRECISION DEFAULT 0,
    "sugar_unit" VARCHAR(255),
    "sodium" DOUBLE PRECISION DEFAULT 0,
    "sodium_unit" VARCHAR(255),
    "status" BIGINT,
    CONSTRAINT "fk_ingredient_nutrition_food_ingredients"
        FOREIGN KEY ("food_ingredient_id") REFERENCES "food_ingredients" ("id")
);

-- changeset codex:013
CREATE TABLE IF NOT EXISTS "food_nutrition_summary" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "food_id" BIGINT,
    "total_calories" DOUBLE PRECISION,
    "total_calories_unit" VARCHAR(255),
    "total_protein" DOUBLE PRECISION,
    "total_protein_unit" VARCHAR(255),
    "total_carbs" DOUBLE PRECISION,
    "total_carbs_unit" VARCHAR(255),
    "total_fat" DOUBLE PRECISION,
    "total_fat_unit" VARCHAR(255),
    "total_fiber" DOUBLE PRECISION DEFAULT 0,
    "total_fiber_unit" VARCHAR(255),
    "total_sugar" DOUBLE PRECISION DEFAULT 0,
    "total_sugar_unit" VARCHAR(255),
    "total_sodium" DOUBLE PRECISION DEFAULT 0,
    "total_sodium_unit" VARCHAR(255),
    CONSTRAINT "fk_food_nutrition_summary_food_library"
        FOREIGN KEY ("food_id") REFERENCES "food_library" ("id")
);

-- changeset codex:014
CREATE TABLE IF NOT EXISTS "food_recommendation" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "food_id" BIGINT,
    "good_points" TEXT,
    "bad_points" TEXT,
    "advice" TEXT,
    "cooking_way" TEXT,
    "status" BIGINT,
    CONSTRAINT "fk_food_recommendation_food_library"
        FOREIGN KEY ("food_id") REFERENCES "food_library" ("id")
);

-- changeset codex:015
CREATE TABLE IF NOT EXISTS "favorite_food" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT,
    "created_at" TIMESTAMP(6),
    "updated_at" TIMESTAMP(6),
    "created_by" VARCHAR(255),
    "updated_by" VARCHAR(255),
    "food_libarary_id" BIGINT,
    CONSTRAINT "fk_favorite_food_user"
        FOREIGN KEY ("user_id") REFERENCES "users" ("id"),
    CONSTRAINT "fk_favorite_food_food_library"
        FOREIGN KEY ("food_libarary_id") REFERENCES "food_library" ("id")
);
