-- liquibase formatted sql

-- changeset codex:033
CREATE TABLE IF NOT EXISTS "restricted_food" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT,
    "food_libarary_id" BIGINT,
    "created_at" TIMESTAMP(6),
    "updated_at" TIMESTAMP(6),
    "created_by" VARCHAR(255),
    "updated_by" VARCHAR(255),
    CONSTRAINT "fk_restricted_food_user"
        FOREIGN KEY ("user_id") REFERENCES "users" ("id"),
    CONSTRAINT "fk_restricted_food_food_library"
        FOREIGN KEY ("food_libarary_id") REFERENCES "food_library" ("id")
);

-- changeset codex:034
CREATE UNIQUE INDEX IF NOT EXISTS "uk_restricted_food_user_food"
    ON "restricted_food" ("user_id", "food_libarary_id");

CREATE UNIQUE INDEX IF NOT EXISTS "uk_favorite_food_user_food"
    ON "favorite_food" ("user_id", "food_libarary_id");
