-- liquibase formatted sql

-- changeset codex:027
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "profile" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "function_code" VARCHAR(255),
    "name" VARCHAR(255) NOT NULL,
    "date_of_birth" DATE,
    "sex" VARCHAR(255),
    "profile_type" VARCHAR(255),
    "created_at" TIMESTAMP(6),
    "created_by" VARCHAR(255),
    "updated_at" TIMESTAMP(6),
    "updated_by" VARCHAR(255),
    "status" BIGINT,
    "profile_code" VARCHAR(255),
    "image_url" TEXT,
    CONSTRAINT "fk_profile_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id")
);

-- changeset codex:028
-- validCheckSum: ANY
ALTER TABLE "profile"
    ADD COLUMN IF NOT EXISTS "image_url" TEXT;

-- changeset codex:029
-- validCheckSum: ANY
UPDATE "profile"
SET "status" = 2
WHERE "status" IS NULL OR "status" = 1;

-- changeset codex:030
-- validCheckSum: ANY
UPDATE "profile"
SET "image_url" = CASE
    WHEN UPPER(COALESCE("profile_type", '')) = 'MOTHER'
        THEN 'https://cdn-icons-png.flaticon.com/512/4140/4140047.png'
    ELSE 'https://cdn-icons-png.flaticon.com/512/4140/4140048.png'
END
WHERE "image_url" IS NULL OR BTRIM("image_url") = '';

-- changeset codex:031
-- validCheckSum: ANY
CREATE INDEX IF NOT EXISTS "idx_profile_user_status"
    ON "profile" ("user_id", "status");
