-- liquibase formatted sql

-- changeset codex:027
ALTER TABLE "users"
    ADD COLUMN IF NOT EXISTS "email_verified" BOOLEAN NOT NULL DEFAULT TRUE;

-- changeset codex:028
CREATE TABLE IF NOT EXISTS "auth_otp" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" VARCHAR(255) NOT NULL,
    "purpose" VARCHAR(50) NOT NULL,
    "code_hash" VARCHAR(255) NOT NULL,
    "expires_at" TIMESTAMP(6) NOT NULL,
    "used_at" TIMESTAMP(6),
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- changeset codex:029
CREATE INDEX IF NOT EXISTS "idx_auth_otp_email_purpose_created_at"
    ON "auth_otp" ("email", "purpose", "created_at" DESC);
