-- liquibase formatted sql

-- changeset codex:060
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "auth_refresh_token" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "token_hash" VARCHAR(64) NOT NULL UNIQUE,
    "user_id" BIGINT NOT NULL,
    "issued_at" TIMESTAMP(6) NOT NULL,
    "last_used_at" TIMESTAMP(6) NOT NULL,
    "expires_at" TIMESTAMP(6) NOT NULL,
    "revoked_at" TIMESTAMP(6),
    CONSTRAINT "fk_auth_refresh_token_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id")
);

-- changeset codex:061
-- validCheckSum: ANY
CREATE INDEX IF NOT EXISTS "idx_auth_refresh_token_user_id"
    ON "auth_refresh_token" ("user_id");

-- changeset codex:062
-- validCheckSum: ANY
CREATE INDEX IF NOT EXISTS "idx_auth_refresh_token_expires_at"
    ON "auth_refresh_token" ("expires_at");
