-- liquibase formatted sql

-- changeset codex:063
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "type_code" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code" VARCHAR(100) NOT NULL UNIQUE,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "status" BIGINT NOT NULL DEFAULT 2,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" VARCHAR(255),
    "updated_at" TIMESTAMP(6),
    "updated_by" VARCHAR(255)
);

-- changeset codex:064
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "type_value" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "type_code_id" BIGINT NOT NULL,
    "value_code" VARCHAR(120) NOT NULL,
    "value_name" VARCHAR(255) NOT NULL,
    "value_text" TEXT,
    "value_number" NUMERIC(19, 4),
    "description" TEXT,
    "sort_order" INTEGER,
    "status" BIGINT NOT NULL DEFAULT 2,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" VARCHAR(255),
    "updated_at" TIMESTAMP(6),
    "updated_by" VARCHAR(255),
    CONSTRAINT "fk_type_value_type_code"
        FOREIGN KEY ("type_code_id") REFERENCES "type_code" ("id"),
    CONSTRAINT "uk_type_value_type_code_value_code"
        UNIQUE ("type_code_id", "value_code")
);

-- changeset codex:065
-- validCheckSum: ANY
CREATE INDEX IF NOT EXISTS "idx_type_value_type_code_status"
    ON "type_value" ("type_code_id", "status");

-- changeset codex:066
-- validCheckSum: ANY
INSERT INTO "type_code" ("code", "name", "description", "status", "created_by")
VALUES
    ('TABLE_STATUS', 'Table status', 'Shared numeric lifecycle/status values from Constants.TABLE_STATUS and existing SQL seeds.', 2, 'SYSTEM'),
    ('API_RESPONSE_CODE', 'API response code', 'Application response code values from Constants.API_RESPONSE.', 2, 'SYSTEM'),
    ('RESPONSE_STATUS', 'Response status', 'Boolean response status values from Constants.STATUS_COMMON.', 2, 'SYSTEM'),
    ('ROLE', 'Role', 'User role names seeded in roles and used by Spring Security.', 2, 'SYSTEM'),
    ('PROFILE_TYPE', 'Profile type', 'Profile type values used by profile.profile_type.', 2, 'SYSTEM'),
    ('SEX', 'Sex', 'Sex values used by profile.sex.', 2, 'SYSTEM'),
    ('FOOD_FUNCTION_CODE', 'Food function code', 'Food function codes from Constants.FOOD_FUNCTION_CODE and food_library.function_code.', 2, 'SYSTEM'),
    ('FOOD_ADVICE_FOR', 'Food advice target', 'Food advice target values from Constants.FOOD_ADVICE_FOR and food_library.advance_for.', 2, 'SYSTEM'),
    ('VACCINE_OFFSET_UNIT', 'Vaccine schedule offset unit', 'Offset units used by vaccine_schedule.offset_unit and Script-18.sql.', 2, 'SYSTEM'),
    ('AI_LESSON_PROGRESS_STATUS', 'AI lesson progress status', 'Progress status values used by ai_lesson_progress.progress_status.', 2, 'SYSTEM'),
    ('HANDBOOK_CATEGORY', 'Handbook category', 'Handbook category values seeded in handbook_posts.', 2, 'SYSTEM'),
    ('VACCINE_TYPE', 'Vaccine type', 'Vaccine type values gathered from Script-18.sql.', 2, 'SYSTEM')
ON CONFLICT ("code") DO UPDATE SET
    "name" = EXCLUDED."name",
    "description" = EXCLUDED."description",
    "status" = EXCLUDED."status",
    "updated_at" = CURRENT_TIMESTAMP,
    "updated_by" = 'SYSTEM';

-- changeset codex:067
-- validCheckSum: ANY
INSERT INTO "type_value" (
    "type_code_id",
    "value_code",
    "value_name",
    "value_text",
    "value_number",
    "description",
    "sort_order",
    "status",
    "created_by"
)
SELECT
    tc."id",
    seed."value_code",
    seed."value_name",
    seed."value_text",
    seed."value_number",
    seed."description",
    seed."sort_order",
    seed."status",
    'SYSTEM'
FROM (
    VALUES
        ('TABLE_STATUS', 'FAILED', 'Failed', NULL, -7, 'Constants.TABLE_STATUS.FAILED', 10, 2),
        ('TABLE_STATUS', 'BLOCKED', 'Blocked', NULL, -6, 'Constants.TABLE_STATUS.BLOCKED', 20, 2),
        ('TABLE_STATUS', 'EXPIRED', 'Expired', NULL, -5, 'Constants.TABLE_STATUS.EXPIRED', 30, 2),
        ('TABLE_STATUS', 'DELETED', 'Deleted', NULL, -4, 'Constants.TABLE_STATUS.DELETED', 40, 2),
        ('TABLE_STATUS', 'UPDATING', 'Updating', NULL, -3, 'Constants.TABLE_STATUS.UPDATING', 50, 2),
        ('TABLE_STATUS', 'CANCELED', 'Canceled', NULL, -2, 'Constants.TABLE_STATUS.CANCELED', 60, 2),
        ('TABLE_STATUS', 'PENDING', 'Pending', NULL, -1, 'Constants.TABLE_STATUS.PENDING; used by vaccine_record seeds in Script-18.sql.', 70, 2),
        ('TABLE_STATUS', 'INACTIVE', 'Inactive', NULL, 0, 'Constants.TABLE_STATUS.INACTIVE', 80, 2),
        ('TABLE_STATUS', 'INITIATED', 'Initiated', NULL, 1, 'Constants.TABLE_STATUS.INITIATED', 90, 2),
        ('TABLE_STATUS', 'ACTIVE', 'Active', NULL, 2, 'Constants.TABLE_STATUS.ACTIVE; used broadly across current migrations and Script-18.sql.', 100, 2),
        ('TABLE_STATUS', 'SUCCESS', 'Success', NULL, 3, 'Constants.TABLE_STATUS.SUCCESS; used by vaccine_record and vaccination_center seeds in Script-18.sql.', 110, 2),

        ('API_RESPONSE_CODE', 'OK', 'OK', '200', 200, 'Constants.API_RESPONSE.RETURN_CODE_OK', 10, 2),
        ('API_RESPONSE_CODE', 'CREATED', 'Created', '201', 201, 'Constants.API_RESPONSE.RETURN_CODE_CREATED', 20, 2),
        ('API_RESPONSE_CODE', 'NO_CONTENT', 'No content', '204', 204, 'Constants.API_RESPONSE.RETURN_CODE_NO_CONTENT', 30, 2),
        ('API_RESPONSE_CODE', 'BAD_REQUEST', 'Bad request', '400', 400, 'Constants.API_RESPONSE.RETURN_CODE_BAD_REQUEST', 40, 2),
        ('API_RESPONSE_CODE', 'UNAUTHORIZED', 'Unauthorized', '401', 401, 'Constants.API_RESPONSE.RETURN_CODE_UNAUTHORIZED', 50, 2),
        ('API_RESPONSE_CODE', 'FORBIDDEN', 'Forbidden', '403', 403, 'Constants.API_RESPONSE.RETURN_CODE_FORBIDDEN', 60, 2),
        ('API_RESPONSE_CODE', 'CONFLICT', 'Conflict', '409', 409, 'Constants.API_RESPONSE.RETURN_CODE_CONFLICT', 70, 2),
        ('API_RESPONSE_CODE', 'ERROR', 'Error', '500', 500, 'Constants.API_RESPONSE.RETURN_CODE_ERROR', 80, 2),

        ('RESPONSE_STATUS', 'TRUE', 'True', 'true', 1, 'Constants.STATUS_COMMON.RESPONSE_STATUS_TRUE', 10, 2),
        ('RESPONSE_STATUS', 'FALSE', 'False', 'false', 0, 'Constants.STATUS_COMMON.RESPONSE_STATUS_FALSE', 20, 2),

        ('ROLE', 'ADMIN', 'Admin', 'ADMIN', NULL, 'Seeded in roles.role_name.', 10, 2),
        ('ROLE', 'MOTHER', 'Mother', 'MOTHER', NULL, 'Seeded in roles.role_name and used as default role/profile owner type.', 20, 2),
        ('ROLE', 'FARTHER', 'Father', 'FARTHER', NULL, 'Existing role code is FARTHER in 001_init_auth_schema.sql.', 30, 2),

        ('PROFILE_TYPE', 'MOTHER', 'Mother', 'MOTHER', NULL, 'Used by profile.profile_type.', 10, 2),
        ('PROFILE_TYPE', 'CHILD', 'Child', 'CHILD', NULL, 'Used by profile.profile_type and Script-18.sql profile seed.', 20, 2),

        ('SEX', 'MALE', 'Male', 'MALE', NULL, 'Allowed by Profile.Sex.', 10, 2),
        ('SEX', 'FEMALE', 'Female', 'FEMALE', NULL, 'Allowed by Profile.Sex and Script-18.sql profile seed.', 20, 2),
        ('SEX', 'OTHER', 'Other', 'OTHER', NULL, 'Allowed by Profile.Sex.', 30, 2),

        ('FOOD_FUNCTION_CODE', 'MOM', 'Mother', NULL, 1, 'Constants.FOOD_FUNCTION_CODE.MOM.', 10, 2),
        ('FOOD_FUNCTION_CODE', 'BABY', 'Baby', NULL, 2, 'Constants.FOOD_FUNCTION_CODE.BABY.', 20, 2),

        ('FOOD_ADVICE_FOR', 'FOR_MOTHER_DIET', 'Mother diet', 'FOR_MOTHER_DIET', NULL, 'Constants.FOOD_ADVICE_FOR.MOM_GET_BACK_IN_SHAPE.', 10, 2),
        ('FOOD_ADVICE_FOR', 'FOR_MOTHER_CHANGE_DIET', 'Mother change diet', 'FOR_MOTHER_CHANGE_DIET', NULL, 'Constants.FOOD_ADVICE_FOR.MOM_CHANGE_DIET.', 20, 2),
        ('FOOD_ADVICE_FOR', 'FOR_MOTHER_POSTPARTUM_BREASTFEEDING', 'Mother postpartum breastfeeding', 'FOR_MOTHER_POSTPARTUM_BREASTFEEDING', NULL, 'Constants.FOOD_ADVICE_FOR.MOM_POSTPARTUM_BREASTFEEDING.', 30, 2),
        ('FOOD_ADVICE_FOR', 'FOR_MOTHER_HEALTHY_ENERGY', 'Mother healthy energy', 'FOR_MOTHER_HEALTHY_ENERGY', NULL, 'Constants.FOOD_ADVICE_FOR.MOM_HEALTHY_ENERGY.', 40, 2),
        ('FOOD_ADVICE_FOR', 'FOR_MOTHER_DIGESTION_RECOVERY', 'Mother digestion recovery', 'FOR_MOTHER_DIGESTION_RECOVERY', NULL, 'Constants.FOOD_ADVICE_FOR.MOM_DIGESTION_RECOVERY.', 50, 2),
        ('FOOD_ADVICE_FOR', 'FOR_MOTHER_INCREASE_MILK_SUPPLY', 'Mother increase milk supply', 'FOR_MOTHER_INCREASE_MILK_SUPPLY', NULL, 'Constants.FOOD_ADVICE_FOR.MOM_INCREASE_MILK_SUPPLY.', 60, 2),
        ('FOOD_ADVICE_FOR', 'FOR_MOTHER_SLEEP_STRESS_SUPPORT', 'Mother sleep stress support', 'FOR_MOTHER_SLEEP_STRESS_SUPPORT', NULL, 'Constants.FOOD_ADVICE_FOR.MOM_SLEEP_STRESS_SUPPORT.', 70, 2),
        ('FOOD_ADVICE_FOR', 'FOR_BABY_6_8_MONTHS', 'Baby 6-8 months', 'FOR_BABY_6_8_MONTHS', NULL, 'Constants.FOOD_ADVICE_FOR.BABY_6_TO_8_MONTHS.', 80, 2),
        ('FOOD_ADVICE_FOR', 'FOR_BABY_9_11_MONTHS', 'Baby 9-11 months', 'FOR_BABY_9_11_MONTHS', NULL, 'Constants.FOOD_ADVICE_FOR.BABY_9_TO_11_MONTHS.', 90, 2),
        ('FOOD_ADVICE_FOR', 'FOR_BABY_12_18_MONTHS', 'Baby 12-18 months', 'FOR_BABY_12_18_MONTHS', NULL, 'Constants.FOOD_ADVICE_FOR.BABY_12_TO_18_MONTHS.', 100, 2),
        ('FOOD_ADVICE_FOR', 'FOR_BABY_19_24_MONTHS', 'Baby 19-24 months', 'FOR_BABY_19_24_MONTHS', NULL, 'Constants.FOOD_ADVICE_FOR.BABY_19_TO_24_MONTHS.', 110, 2),
        ('FOOD_ADVICE_FOR', 'FOR_BABY_6_8_MONTHS_DEVELOPMENT', 'Baby 6-8 months development', 'FOR_BABY_6_8_MONTHS_DEVELOPMENT', NULL, 'Constants.FOOD_ADVICE_FOR.BABY_6_TO_8_MONTHS_DEVELOPMENT.', 120, 2),
        ('FOOD_ADVICE_FOR', 'FOR_BABY_9_11_MONTHS_DEVELOPMENT', 'Baby 9-11 months development', 'FOR_BABY_9_11_MONTHS_DEVELOPMENT', NULL, 'Constants.FOOD_ADVICE_FOR.BABY_9_TO_11_MONTHS_DEVELOPMENT.', 130, 2),
        ('FOOD_ADVICE_FOR', 'FOR_BABY_12_18_MONTHS_DEVELOPMENT', 'Baby 12-18 months development', 'FOR_BABY_12_18_MONTHS_DEVELOPMENT', NULL, 'Constants.FOOD_ADVICE_FOR.BABY_12_TO_18_MONTHS_DEVELOPMENT.', 140, 2),
        ('FOOD_ADVICE_FOR', 'FOR_BABY_19_24_MONTHS_DEVELOPMENT', 'Baby 19-24 months development', 'FOR_BABY_19_24_MONTHS_DEVELOPMENT', NULL, 'Constants.FOOD_ADVICE_FOR.BABY_19_TO_24_MONTHS_DEVELOPMENT.', 150, 2),

        ('VACCINE_OFFSET_UNIT', 'DAY', 'Day', 'DAY', NULL, 'Used by VaccineSchedule.offsetUnit and Script-18.sql.', 10, 2),
        ('VACCINE_OFFSET_UNIT', 'MONTH', 'Month', 'MONTH', NULL, 'Used by VaccineSchedule.offsetUnit and Script-18.sql.', 20, 2),
        ('VACCINE_OFFSET_UNIT', 'YEAR', 'Year', 'YEAR', NULL, 'Documented by VaccineSchedule.offsetUnit comment.', 30, 2),

        ('AI_LESSON_PROGRESS_STATUS', 'INITIATED', 'Initiated', NULL, 1, 'Seeded in 018_seed_ai_lesson_progress.sql.', 10, 2),
        ('AI_LESSON_PROGRESS_STATUS', 'ACTIVE', 'Active', NULL, 2, 'Seeded in 018_seed_ai_lesson_progress.sql.', 20, 2),
        ('AI_LESSON_PROGRESS_STATUS', 'SUCCESS', 'Success', NULL, 3, 'Seeded in 018_seed_ai_lesson_progress.sql.', 30, 2),

        ('HANDBOOK_CATEGORY', 'DINH_DUONG', 'Dinh dưỡng', 'Dinh dưỡng', NULL, 'Seeded in 019_create_handbook.sql.', 10, 2),
        ('HANDBOOK_CATEGORY', 'SUC_KHOE', 'Sức khỏe', 'Sức khỏe', NULL, 'Seeded in 019_create_handbook.sql.', 20, 2),
        ('HANDBOOK_CATEGORY', 'GIAC_NGU', 'Giấc ngủ', 'Giấc ngủ', NULL, 'Seeded in 019_create_handbook.sql.', 30, 2),

        ('VACCINE_TYPE', 'BCG', 'BCG', 'BCG', NULL, 'Vaccine phòng bệnh Lao. From Script-18.sql.', 10, 2),
        ('VACCINE_TYPE', 'VIEM_GAN_B', 'Viêm gan B', 'Viêm gan B', NULL, 'Vaccine phòng bệnh Viêm gan B. From Script-18.sql.', 20, 2),
        ('VACCINE_TYPE', 'INFANRIX_HEXA', '6 trong 1 (Infanrix hexa)', '6 trong 1 (Infanrix hexa)', NULL, 'Phòng Bạch hầu, Ho gà, Uốn ván, Bại liệt, Viêm gan B, Hib. From Script-18.sql.', 30, 2),
        ('VACCINE_TYPE', 'CUM', 'Cúm', 'Cúm', NULL, 'Vaccine phòng bệnh Cúm mùa. From Script-18.sql.', 40, 2),
        ('VACCINE_TYPE', 'MMR', 'Sởi - Quai bị - Rubella', 'Sởi - Quai bị - Rubella', NULL, 'Vaccine MMR II. From Script-18.sql.', 50, 2),
        ('VACCINE_TYPE', 'SOI', 'Sởi', 'Sởi', NULL, 'Vắc xin phòng bệnh sởi. From Script-18.sql.', 60, 2),
        ('VACCINE_TYPE', 'QUAI_BI', 'Quai bị', 'Quai bị', NULL, 'Vắc xin phòng bệnh quai bị. From Script-18.sql.', 70, 2),
        ('VACCINE_TYPE', 'RUBELLA', 'Rubella', 'Rubella', NULL, 'Vắc xin phòng bệnh Rubella. From Script-18.sql.', 80, 2),
        ('VACCINE_TYPE', 'THUY_DAU', 'Thủy đậu', 'Thủy đậu', NULL, 'Vắc xin phòng bệnh thủy đậu. From Script-18.sql.', 90, 2),
        ('VACCINE_TYPE', 'VIEM_NAO_NHAT_BAN', 'Viêm não Nhật Bản', 'Viêm não Nhật Bản', NULL, 'Phòng bệnh viêm não Nhật Bản. From Script-18.sql.', 100, 2),
        ('VACCINE_TYPE', 'CUM_MUA', 'Cúm mùa', 'Cúm', NULL, 'Vắc xin phòng cúm mùa. From Script-18.sql duplicate Cúm row.', 110, 2),
        ('VACCINE_TYPE', 'VIEM_GAN_A', 'Viêm gan A', 'Viêm gan A', NULL, 'Vắc xin phòng viêm gan A. From Script-18.sql.', 120, 1),
        ('VACCINE_TYPE', 'THUONG_HAN', 'Thương hàn', 'Thương hàn', NULL, 'Vắc xin phòng bệnh thương hàn. From Script-18.sql.', 130, 2),
        ('VACCINE_TYPE', 'TA', 'Tả', 'Tả', NULL, 'Vắc xin phòng bệnh tả (uống). From Script-18.sql.', 140, 2),
        ('VACCINE_TYPE', 'DAI', 'Dại', 'Dại', NULL, 'Vắc xin phòng bệnh dại. From Script-18.sql.', 150, 2)
) AS seed (
    "type_code",
    "value_code",
    "value_name",
    "value_text",
    "value_number",
    "description",
    "sort_order",
    "status"
)
JOIN "type_code" tc ON tc."code" = seed."type_code"
ON CONFLICT ("type_code_id", "value_code") DO UPDATE SET
    "value_name" = EXCLUDED."value_name",
    "value_text" = EXCLUDED."value_text",
    "value_number" = EXCLUDED."value_number",
    "description" = EXCLUDED."description",
    "sort_order" = EXCLUDED."sort_order",
    "status" = EXCLUDED."status",
    "updated_at" = CURRENT_TIMESTAMP,
    "updated_by" = 'SYSTEM';
