-- liquibase formatted sql

-- changeset codex:068
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "vaccine_type" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255),
    "description" TEXT,
    "total_dose" INTEGER,
    "required_age" VARCHAR(255),
    "for_mother" BOOLEAN,
    "for_child" BOOLEAN,
    "created_at" DATE,
    "created_by" BIGINT,
    "updated_at" DATE,
    "updated_by" BIGINT,
    "status" BIGINT
);

-- changeset codex:069
-- validCheckSum: ANY
INSERT INTO "vaccine_type" (
    "id",
    "name",
    "description",
    "total_dose",
    "required_age",
    "for_mother",
    "for_child",
    "created_at",
    "created_by",
    "status"
)
VALUES
    (1, 'BCG', 'Vaccine phòng bệnh Lao', 1, NULL, false, true, CURRENT_DATE, 1, 2),
    (2, 'Viêm gan B', 'Vaccine phòng bệnh Viêm gan B', 3, NULL, true, true, CURRENT_DATE, 1, 2),
    (3, '6 trong 1 (Infanrix hexa)', 'Phòng Bạch hầu, Ho gà, Uốn ván, Bại liệt, Viêm gan B, Hib', 3, NULL, false, true, CURRENT_DATE, 1, 2),
    (4, 'Cúm', 'Vaccine phòng bệnh Cúm mùa', 1, NULL, true, true, CURRENT_DATE, 1, 2),
    (5, 'Sởi - Quai bị - Rubella', 'Vaccine MMR II', 2, NULL, false, true, CURRENT_DATE, 1, 2),
    (6, 'Sởi', 'Vắc xin phòng bệnh sởi', 2, '9 tháng', false, true, CURRENT_DATE, 1, 2),
    (7, 'Quai bị', 'Vắc xin phòng bệnh quai bị', 2, '12 tháng', false, true, CURRENT_DATE, 1, 2),
    (8, 'Rubella', 'Vắc xin phòng bệnh Rubella', 2, '12 tháng', true, true, CURRENT_DATE, 1, 2),
    (9, 'Thủy đậu', 'Vắc xin phòng bệnh thủy đậu', 2, '12 tháng', false, true, CURRENT_DATE, 1, 2),
    (10, 'Viêm não Nhật Bản', 'Phòng bệnh viêm não Nhật Bản', 3, '12 tháng', false, true, CURRENT_DATE, 1, 2),
    (11, 'Cúm', 'Vắc xin phòng cúm mùa', 1, '6 tháng', true, true, CURRENT_DATE, 1, 2),
    (12, 'Viêm gan A', 'Vắc xin phòng viêm gan A', 2, '12 tháng', false, true, CURRENT_DATE, 1, 1),
    (13, 'Thương hàn', 'Vắc xin phòng bệnh thương hàn', 1, '24 tháng', false, true, CURRENT_DATE, 1, 2),
    (14, 'Tả', 'Vắc xin phòng bệnh tả (uống)', 2, '24 tháng', false, true, CURRENT_DATE, 1, 2),
    (15, 'Dại', 'Vắc xin phòng bệnh dại', 5, 'Mọi lứa tuổi', true, true, CURRENT_DATE, 1, 2)
ON CONFLICT ("id") DO UPDATE SET
    "name" = EXCLUDED."name",
    "description" = EXCLUDED."description",
    "total_dose" = EXCLUDED."total_dose",
    "required_age" = EXCLUDED."required_age",
    "for_mother" = EXCLUDED."for_mother",
    "for_child" = EXCLUDED."for_child",
    "created_at" = COALESCE("vaccine_type"."created_at", EXCLUDED."created_at"),
    "created_by" = COALESCE("vaccine_type"."created_by", EXCLUDED."created_by"),
    "updated_at" = CURRENT_DATE,
    "updated_by" = 1,
    "status" = EXCLUDED."status";

-- changeset codex:070
-- validCheckSum: ANY
SELECT setval(
    pg_get_serial_sequence('"vaccine_type"', 'id'),
    COALESCE((SELECT MAX("id") FROM "vaccine_type"), 1),
    true
);
