-- liquibase formatted sql

-- changeset codex:068
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "notification" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "type" VARCHAR(80) NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "body" TEXT,
    "data_json" TEXT,
    "priority" BIGINT NOT NULL DEFAULT 2,
    "source_type" VARCHAR(80),
    "source_id" BIGINT,
    "status" BIGINT NOT NULL DEFAULT -1,
    "read_at" TIMESTAMP(6),
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_notification_user"
        FOREIGN KEY ("user_id") REFERENCES "users" ("id")
);

-- changeset codex:069
-- validCheckSum: ANY
CREATE INDEX IF NOT EXISTS "idx_notification_user_status_created"
    ON "notification" ("user_id", "status", "created_at" DESC);

-- changeset codex:070
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "device_token" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "token" TEXT NOT NULL UNIQUE,
    "platform" VARCHAR(20) NOT NULL,
    "device_id" VARCHAR(120) NOT NULL,
    "app_version" VARCHAR(40),
    "status" BIGINT NOT NULL DEFAULT 2,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(6),
    "last_used_at" TIMESTAMP(6),
    CONSTRAINT "fk_device_token_user"
        FOREIGN KEY ("user_id") REFERENCES "users" ("id"),
    CONSTRAINT "uk_device_token_user_device"
        UNIQUE ("user_id", "device_id")
);

-- changeset codex:071
-- validCheckSum: ANY
CREATE INDEX IF NOT EXISTS "idx_device_token_user_status"
    ON "device_token" ("user_id", "status");

-- changeset codex:072
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "notification_setting" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL UNIQUE,
    "push_enabled" BOOLEAN NOT NULL DEFAULT TRUE,
    "vaccine_enabled" BOOLEAN NOT NULL DEFAULT TRUE,
    "appointment_enabled" BOOLEAN NOT NULL DEFAULT TRUE,
    "chat_enabled" BOOLEAN NOT NULL DEFAULT TRUE,
    "promotion_enabled" BOOLEAN NOT NULL DEFAULT FALSE,
    "system_enabled" BOOLEAN NOT NULL DEFAULT TRUE,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(6),
    CONSTRAINT "fk_notification_setting_user"
        FOREIGN KEY ("user_id") REFERENCES "users" ("id")
);
