-- liquibase formatted sql

-- changeset codex:075
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "vaccine_schedule" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "vaccine_type_id" BIGINT,
    "dose_number" INTEGER,
    "offset_value" INTEGER,
    "offset_unit" VARCHAR(255),
    CONSTRAINT "fk_vaccine_schedule_vaccine_type"
        FOREIGN KEY ("vaccine_type_id") REFERENCES "vaccine_type" ("id")
);

-- changeset codex:076
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "vaccination_center" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "address" VARCHAR(255) NOT NULL,
    "distance" DOUBLE PRECISION,
    "status" BIGINT,
    "created_at" TIMESTAMP(6),
    "updated_at" TIMESTAMP(6)
);

-- changeset codex:077
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "vaccine_pricing" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "vaccine_type_id" BIGINT NOT NULL,
    "center_id" BIGINT NOT NULL,
    "price" NUMERIC(19, 2),
    "discount_price" NUMERIC(19, 2),
    "note" TEXT,
    "status" BIGINT,
    "created_at" TIMESTAMP(6),
    "updated_at" TIMESTAMP(6),
    CONSTRAINT "fk_vaccine_pricing_vaccine_type"
        FOREIGN KEY ("vaccine_type_id") REFERENCES "vaccine_type" ("id"),
    CONSTRAINT "fk_vaccine_pricing_center"
        FOREIGN KEY ("center_id") REFERENCES "vaccination_center" ("id")
);

-- changeset codex:078
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "vaccine_record" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "profile_id" BIGINT,
    "vaccine_type_id" BIGINT,
    "injection_date" DATE,
    "location" VARCHAR(255),
    "price" NUMERIC(19, 2),
    "note" VARCHAR(255),
    "created_at" DATE,
    "created_by" BIGINT,
    "updated_at" DATE,
    "updated_by" BIGINT,
    "status" BIGINT,
    CONSTRAINT "fk_vaccine_record_vaccine_type"
        FOREIGN KEY ("vaccine_type_id") REFERENCES "vaccine_type" ("id")
);

-- changeset codex:079
-- validCheckSum: ANY
INSERT INTO "vaccine_type" (
    "id",
    "name",
    "description",
    "total_dose",
    "required_age",
    "for_mother",
    "for_child",
    "created_at",
    "created_by",
    "status"
)
VALUES
    (1, 'BCG', 'Vaccine phÃ²ng bá»‡nh Lao', 1, NULL, false, true, CURRENT_DATE, 1, 2),
    (2, 'ViÃªm gan B', 'Vaccine phÃ²ng bá»‡nh ViÃªm gan B', 3, NULL, true, true, CURRENT_DATE, 1, 2),
    (3, '6 trong 1 (Infanrix hexa)', 'PhÃ²ng Báº¡ch háº§u, Ho gÃ , Uá»‘n vÃ¡n, Báº¡i liá»‡t, ViÃªm gan B, Hib', 3, NULL, false, true, CURRENT_DATE, 1, 2),
    (4, 'CÃºm', 'Vaccine phÃ²ng bá»‡nh CÃºm mÃ¹a', 1, NULL, true, true, CURRENT_DATE, 1, 2),
    (5, 'Sá»Ÿi - Quai bá»‹ - Rubella', 'Vaccine MMR II', 2, NULL, false, true, CURRENT_DATE, 1, 2),
    (6, 'Sá»Ÿi', 'Váº¯c xin phÃ²ng bá»‡nh sá»Ÿi', 2, '9 thÃ¡ng', false, true, CURRENT_DATE, 1, 2),
    (7, 'Quai bá»‹', 'Váº¯c xin phÃ²ng bá»‡nh quai bá»‹', 2, '12 thÃ¡ng', false, true, CURRENT_DATE, 1, 2),
    (8, 'Rubella', 'Váº¯c xin phÃ²ng bá»‡nh Rubella', 2, '12 thÃ¡ng', true, true, CURRENT_DATE, 1, 2),
    (9, 'Thá»§y Ä‘áº­u', 'Váº¯c xin phÃ²ng bá»‡nh thá»§y Ä‘áº­u', 2, '12 thÃ¡ng', false, true, CURRENT_DATE, 1, 2),
    (10, 'ViÃªm nÃ£o Nháº­t Báº£n', 'PhÃ²ng bá»‡nh viÃªm nÃ£o Nháº­t Báº£n', 3, '12 thÃ¡ng', false, true, CURRENT_DATE, 1, 2),
    (11, 'CÃºm', 'Váº¯c xin phÃ²ng cÃºm mÃ¹a', 1, '6 thÃ¡ng', true, true, CURRENT_DATE, 1, 2),
    (12, 'ViÃªm gan A', 'Váº¯c xin phÃ²ng viÃªm gan A', 2, '12 thÃ¡ng', false, true, CURRENT_DATE, 1, 2),
    (13, 'ThÆ°Æ¡ng hÃ n', 'Váº¯c xin phÃ²ng bá»‡nh thÆ°Æ¡ng hÃ n', 1, '24 thÃ¡ng', false, true, CURRENT_DATE, 1, 2),
    (14, 'Táº£', 'Váº¯c xin phÃ²ng bá»‡nh táº£ (uá»‘ng)', 2, '24 thÃ¡ng', false, true, CURRENT_DATE, 1, 2),
    (15, 'Dáº¡i', 'Váº¯c xin phÃ²ng bá»‡nh dáº¡i', 5, 'Má»i lá»©a tuá»•i', true, true, CURRENT_DATE, 1, 2)
ON CONFLICT ("id") DO UPDATE SET
    "name" = EXCLUDED."name",
    "description" = EXCLUDED."description",
    "total_dose" = EXCLUDED."total_dose",
    "required_age" = EXCLUDED."required_age",
    "for_mother" = EXCLUDED."for_mother",
    "for_child" = EXCLUDED."for_child",
    "created_at" = COALESCE("vaccine_type"."created_at", EXCLUDED."created_at"),
    "created_by" = COALESCE("vaccine_type"."created_by", EXCLUDED."created_by"),
    "updated_at" = CURRENT_DATE,
    "updated_by" = 1,
    "status" = EXCLUDED."status";

-- changeset codex:080
-- validCheckSum: ANY
INSERT INTO "vaccine_schedule" ("id", "vaccine_type_id", "dose_number", "offset_value", "offset_unit")
VALUES
    (1, 1, 1, 0, 'DAY'),
    (2, 2, 1, 0, 'DAY'),
    (3, 2, 2, 1, 'MONTH'),
    (4, 2, 3, 6, 'MONTH'),
    (5, 3, 1, 2, 'MONTH'),
    (6, 3, 2, 3, 'MONTH'),
    (7, 3, 3, 4, 'MONTH'),
    (8, 5, 1, 9, 'MONTH'),
    (9, 5, 2, 18, 'MONTH')
ON CONFLICT ("id") DO UPDATE SET
    "vaccine_type_id" = EXCLUDED."vaccine_type_id",
    "dose_number" = EXCLUDED."dose_number",
    "offset_value" = EXCLUDED."offset_value",
    "offset_unit" = EXCLUDED."offset_unit";

-- changeset codex:081
-- validCheckSum: ANY
INSERT INTO "vaccination_center" ("id", "name", "address", "distance", "status", "created_at")
VALUES
    (1, 'VNVC TrÆ°á»ng Chinh', '180 TrÆ°á»ng Chinh, Äá»‘ng Äa, HÃ  Ná»™i', 2.5, 2, CURRENT_TIMESTAMP),
    (2, 'Trung tÃ¢m Y táº¿ Dá»± phÃ²ng HÃ  Ná»™i', '70 Nguyá»…n ChÃ­ Thanh, Äá»‘ng Äa, HÃ  Ná»™i', 1.2, 2, CURRENT_TIMESTAMP),
    (3, 'Bá»‡nh viá»‡n Nhi Trung Æ°Æ¡ng', '18/879 La ThÃ nh, Äá»‘ng Äa, HÃ  Ná»™i', 3.0, 2, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO UPDATE SET
    "name" = EXCLUDED."name",
    "address" = EXCLUDED."address",
    "distance" = EXCLUDED."distance",
    "status" = EXCLUDED."status",
    "updated_at" = CURRENT_TIMESTAMP;

-- changeset codex:082
-- validCheckSum: ANY
INSERT INTO "vaccine_pricing" ("id", "vaccine_type_id", "center_id", "price", "discount_price", "note", "status", "created_at")
VALUES
    (1, 3, 1, 1050000.00, 1000000.00, 'GiÃ¡ Æ°u Ä‘Ã£i gÃ³i tiÃªm', 2, CURRENT_TIMESTAMP),
    (2, 3, 2, 980000.00, NULL, 'GiÃ¡ niÃªm yáº¿t', 2, CURRENT_TIMESTAMP),
    (3, 4, 1, 350000.00, 320000.00, 'CÃºm mÃ¹a má»›i nháº¥t', 2, CURRENT_TIMESTAMP),
    (4, 5, 3, 450000.00, NULL, NULL, 2, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO UPDATE SET
    "vaccine_type_id" = EXCLUDED."vaccine_type_id",
    "center_id" = EXCLUDED."center_id",
    "price" = EXCLUDED."price",
    "discount_price" = EXCLUDED."discount_price",
    "note" = EXCLUDED."note",
    "status" = EXCLUDED."status",
    "updated_at" = CURRENT_TIMESTAMP;

-- changeset codex:083
-- validCheckSum: ANY
INSERT INTO "vaccine_record" (
    "id",
    "profile_id",
    "vaccine_type_id",
    "injection_date",
    "location",
    "price",
    "note",
    "created_at",
    "created_by",
    "status"
)
VALUES
    (1, 1, 1, '2023-10-01', 'Bá»‡nh viá»‡n Phá»¥ sáº£n TW', 0.00, 'TiÃªm ngay sau sinh (Miá»…n phÃ­)', CURRENT_DATE, -1, 3),
    (2, 1, 2, '2023-10-01', 'Bá»‡nh viá»‡n Phá»¥ sáº£n TW', 0.00, 'MÅ©i 1 sÆ¡ sinh', CURRENT_DATE, -1, 3),
    (3, 1, 2, '2023-11-05', 'VNVC TrÆ°á»ng Chinh', 250000.00, 'MÅ©i 2 trá»… 5 ngÃ y', CURRENT_DATE, 3, 3),
    (4, 1, 3, '2023-12-10', 'VNVC TrÆ°á»ng Chinh', 1050000.00, 'MÅ©i 1 - 6 trong 1', CURRENT_DATE, 3, 3),
    (5, 1, 6, '2023-10-01', 'Trung tÃ¢m y táº¿ dá»± phÃ²ng', 250000.00, 'MÅ©i 1', CURRENT_DATE, 1, 3),
    (6, 1, 7, '2023-10-15', 'VNVC HÃ  Ná»™i', 350000.00, 'TiÃªm dá»‹ch vá»¥', CURRENT_DATE, 1, 3),
    (7, 1, 8, '2023-10-15', 'VNVC HÃ  Ná»™i', 350000.00, 'Káº¿t há»£p MMR', CURRENT_DATE, 1, 3),
    (8, 1, 9, '2023-11-05', 'Bá»‡nh viá»‡n Nhi Trung Æ°Æ¡ng', 450000.00, 'MÅ©i 1', CURRENT_DATE, 1, 3),
    (9, 1, 10, '2023-11-20', 'Tráº¡m y táº¿ xÃ£', 0.00, 'TiÃªm chá»§ng má»Ÿ rá»™ng', CURRENT_DATE, 1, 3),
    (10, 1, 11, '2023-12-01', 'PhÃ²ng khÃ¡m Ä‘a khoa', 190000.00, 'CÃºm mÃ¹a hÃ ng nÄƒm', CURRENT_DATE, 1, -1),
    (11, 1, 12, '2023-12-15', 'VNVC', 280000.00, 'MÅ©i nháº¯c láº¡i', CURRENT_DATE, 1, -1),
    (12, 1, 13, '2024-01-10', 'Trung tÃ¢m y táº¿ quáº­n', 150000.00, 'Äá»‹nh ká»³', CURRENT_DATE, 1, -1),
    (13, 1, 14, '2024-02-01', 'Tráº¡m y táº¿', 50000.00, 'Uá»‘ng liá»u 1', CURRENT_DATE, 1, -1),
    (14, 1, 15, '2024-03-05', 'Viá»‡n Vá»‡ sinh Dá»‹ch tá»…', 600000.00, 'TiÃªm phÃ²ng sau phÆ¡i nhiá»…m', CURRENT_DATE, 1, -1),
    (16, 2, 6, '2024-03-01', 'Trung tÃ¢m y táº¿ Q1', 250000.00, 'MÅ©i 1 - ÄÃ£ tiÃªm', CURRENT_DATE, 1, 3),
    (17, 2, 7, '2024-03-10', 'VNVC', 350000.00, 'Há»§y do bÃ© sá»‘t', CURRENT_DATE, 1, -2),
    (18, 2, 8, '2024-03-15', 'Bá»‡nh viá»‡n Nhi', 300000.00, 'MÅ©i nháº¯c láº¡i', CURRENT_DATE, 1, 3),
    (19, 2, 9, '2024-04-01', 'Tráº¡m y táº¿ phÆ°á»ng', 0.00, 'Lá»‹ch tiÃªm chá»§ng má»Ÿ rá»™ng', CURRENT_DATE, 1, 3),
    (20, 2, 10, '2024-04-05', 'PhÃ²ng khÃ¡m Ä‘a khoa', 450000.00, 'Gia Ä‘Ã¬nh báº­n, khÃ´ng Ä‘i Ä‘Æ°á»£c', CURRENT_DATE, 1, -2),
    (21, 2, 11, '2024-04-10', 'VNVC HÃ  Ná»™i', 190000.00, 'TiÃªm cÃºm mÃ¹a', CURRENT_DATE, 1, 3),
    (22, 2, 12, '2024-05-01', 'Trung tÃ¢m tiÃªm chá»§ng', 280000.00, 'Há»§y lá»‹ch háº¹n', CURRENT_DATE, 1, -2),
    (23, 2, 13, '2024-05-15', 'Bá»‡nh viá»‡n Tá»« DÅ©', 150000.00, 'ÄÃ£ hoÃ n thÃ nh', CURRENT_DATE, 1, 3),
    (24, 2, 14, '2024-06-01', 'Tráº¡m y táº¿', 50000.00, 'Uá»‘ng liá»u 1', CURRENT_DATE, 1, 3),
    (25, 2, 15, '2024-06-10', 'Viá»‡n Pasteur', 600000.00, 'Háº¿t thuá»‘c táº¡i Ä‘iá»ƒm tiÃªm', CURRENT_DATE, 1, -2)
ON CONFLICT ("id") DO UPDATE SET
    "profile_id" = EXCLUDED."profile_id",
    "vaccine_type_id" = EXCLUDED."vaccine_type_id",
    "injection_date" = EXCLUDED."injection_date",
    "location" = EXCLUDED."location",
    "price" = EXCLUDED."price",
    "note" = EXCLUDED."note",
    "created_at" = COALESCE("vaccine_record"."created_at", EXCLUDED."created_at"),
    "created_by" = COALESCE("vaccine_record"."created_by", EXCLUDED."created_by"),
    "updated_at" = CURRENT_DATE,
    "updated_by" = 1,
    "status" = EXCLUDED."status";

-- changeset codex:084
-- validCheckSum: ANY
SELECT setval(pg_get_serial_sequence('"vaccine_type"', 'id'), COALESCE((SELECT MAX("id") FROM "vaccine_type"), 1), true);

-- changeset codex:085
-- validCheckSum: ANY
SELECT setval(pg_get_serial_sequence('"vaccine_schedule"', 'id'), COALESCE((SELECT MAX("id") FROM "vaccine_schedule"), 1), true);

-- changeset codex:086
-- validCheckSum: ANY
SELECT setval(pg_get_serial_sequence('"vaccination_center"', 'id'), COALESCE((SELECT MAX("id") FROM "vaccination_center"), 1), true);

-- changeset codex:087
-- validCheckSum: ANY
SELECT setval(pg_get_serial_sequence('"vaccine_pricing"', 'id'), COALESCE((SELECT MAX("id") FROM "vaccine_pricing"), 1), true);

-- changeset codex:088
-- validCheckSum: ANY
SELECT setval(pg_get_serial_sequence('"vaccine_record"', 'id'), COALESCE((SELECT MAX("id") FROM "vaccine_record"), 1), true);
