-- liquibase formatted sql

-- changeset codex:074
CREATE TABLE IF NOT EXISTS "health_record" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "profile_id" BIGINT NOT NULL,
    "height" DOUBLE PRECISION,
    "weight" DOUBLE PRECISION,
    "bmi" DOUBLE PRECISION,
    "record_date" DATE NOT NULL,
    "created_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(6),
    CONSTRAINT "fk_health_record_profile"
        FOREIGN KEY ("profile_id") REFERENCES "profile" ("id")
);

-- changeset codex:075
CREATE INDEX IF NOT EXISTS "idx_health_record_profile_date"
    ON "health_record" ("profile_id", "record_date" DESC);

-- changeset codex:076
CREATE TABLE IF NOT EXISTS "illness_event" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "profile_id" BIGINT NOT NULL,
    "start_at" DATE NOT NULL,
    "end_at" DATE,
    "illness_type" VARCHAR(255) NOT NULL,
    "status" BIGINT DEFAULT 2,
    "description" TEXT,
    "created_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(6),
    CONSTRAINT "fk_illness_event_profile"
        FOREIGN KEY ("profile_id") REFERENCES "profile" ("id")
);

-- changeset codex:077
CREATE INDEX IF NOT EXISTS "idx_illness_event_profile_start_end"
    ON "illness_event" ("profile_id", "start_at" DESC, "end_at");

-- changeset codex:078
CREATE INDEX IF NOT EXISTS "idx_illness_event_profile_status"
    ON "illness_event" ("profile_id", "status");

-- changeset codex:079
ALTER TABLE IF EXISTS "health_record"
    DROP COLUMN IF EXISTS "heart_rate";
