-- liquibase formatted sql

-- changeset codex:080
CREATE TABLE IF NOT EXISTS "diary_entry" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "profile_id" BIGINT NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "content" TEXT NOT NULL,
    "image_url" VARCHAR(1000),
    "milestone" VARCHAR(255),
    "entry_date" DATE NOT NULL,
    "status" BIGINT DEFAULT 2,
    "created_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(6),
    CONSTRAINT "fk_diary_entry_profile"
        FOREIGN KEY ("profile_id") REFERENCES "profile" ("id")
);

-- changeset codex:081
CREATE INDEX IF NOT EXISTS "idx_diary_entry_profile_date_status"
    ON "diary_entry" ("profile_id", "entry_date" DESC, "status");
