-- liquibase formatted sql

-- changeset codex:031-vaccine-final-schema
-- validCheckSum: ANY
DROP TABLE IF EXISTS "vaccine_group_dose_schedules" CASCADE;
DROP TABLE IF EXISTS "vaccine_product_groups" CASCADE;
DROP TABLE IF EXISTS "vaccine_groups" CASCADE;
DROP TABLE IF EXISTS "location_package_prices" CASCADE;
DROP TABLE IF EXISTS "location_vaccine_prices" CASCADE;
DROP TABLE IF EXISTS "package_structures" CASCADE;
DROP TABLE IF EXISTS "vaccine_packages" CASCADE;
DROP TABLE IF EXISTS "locations" CASCADE;
DROP TABLE IF EXISTS "vaccine_pricing" CASCADE;
DROP TABLE IF EXISTS "vaccine_schedule" CASCADE;
DROP TABLE IF EXISTS "vaccination_center" CASCADE;
DROP TABLE IF EXISTS "vaccine_type" CASCADE;

CREATE TABLE IF NOT EXISTS "vaccines" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "manufacturer" VARCHAR(255),
    "origin" VARCHAR(255),
    "description" TEXT,
    "status" BIGINT,
    "created_at" TIMESTAMP(6),
    "updated_at" TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS "child_vaccine_diseases" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code" VARCHAR(100) NOT NULL UNIQUE,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "is_required" BOOLEAN DEFAULT TRUE,
    "display_order" INTEGER,
    "status" BIGINT DEFAULT 2,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "vaccine_disease_coverage" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "vaccine_id" BIGINT NOT NULL,
    "disease_id" BIGINT NOT NULL,
    "product_family_code" VARCHAR(100),
    "interchange_rule" BIGINT NOT NULL DEFAULT 2,
    "status" BIGINT DEFAULT 2,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    CONSTRAINT "fk_vaccine_disease_coverage_vaccine" FOREIGN KEY ("vaccine_id") REFERENCES "vaccines" ("id"),
    CONSTRAINT "fk_vaccine_disease_coverage_disease" FOREIGN KEY ("disease_id") REFERENCES "child_vaccine_diseases" ("id"),
    CONSTRAINT "uk_vaccine_disease_coverage" UNIQUE ("vaccine_id", "disease_id")
);

CREATE TABLE IF NOT EXISTS "child_disease_dose_schedules" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "disease_id" BIGINT NOT NULL,
    "dose_order" INTEGER NOT NULL,
    "recommended_age_months" INTEGER,
    "interval_days" INTEGER,
    "dose_label" VARCHAR(255),
    "note" TEXT,
    "status" BIGINT DEFAULT 2,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    CONSTRAINT "fk_child_disease_dose_disease" FOREIGN KEY ("disease_id") REFERENCES "child_vaccine_diseases" ("id"),
    CONSTRAINT "uk_child_disease_dose" UNIQUE ("disease_id", "dose_order")
);

CREATE TABLE IF NOT EXISTS "child_disease_dose_vaccine_options" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "disease_id" BIGINT NOT NULL,
    "dose_schedule_id" BIGINT,
    "dose_order" INTEGER NOT NULL,
    "vaccine_id" BIGINT NOT NULL,
    "is_preferred" BOOLEAN DEFAULT FALSE,
    "display_order" INTEGER,
    "note" TEXT,
    "status" BIGINT DEFAULT 2,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    CONSTRAINT "fk_child_disease_dose_option_disease" FOREIGN KEY ("disease_id") REFERENCES "child_vaccine_diseases" ("id"),
    CONSTRAINT "fk_child_disease_dose_option_schedule" FOREIGN KEY ("dose_schedule_id") REFERENCES "child_disease_dose_schedules" ("id"),
    CONSTRAINT "fk_child_disease_dose_option_vaccine" FOREIGN KEY ("vaccine_id") REFERENCES "vaccines" ("id"),
    CONSTRAINT "uk_child_disease_dose_vaccine_option" UNIQUE ("disease_id", "dose_order", "vaccine_id")
);

CREATE TABLE IF NOT EXISTS "profile_vaccine_disease_status" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "profile_id" BIGINT NOT NULL,
    "disease_id" BIGINT NOT NULL,
    "status" BIGINT NOT NULL DEFAULT 2,
    "stopped_at" TIMESTAMP,
    "stopped_dose_order" INTEGER,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    CONSTRAINT "fk_profile_vaccine_disease_status_profile" FOREIGN KEY ("profile_id") REFERENCES "profile" ("id"),
    CONSTRAINT "fk_profile_vaccine_disease_status_disease" FOREIGN KEY ("disease_id") REFERENCES "child_vaccine_diseases" ("id"),
    CONSTRAINT "uk_profile_vaccine_disease_status" UNIQUE ("profile_id", "disease_id")
);

CREATE TABLE IF NOT EXISTS "vaccine_record" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "profile_id" BIGINT,
    "disease_id" BIGINT,
    "dose_order" INTEGER,
    "source" BIGINT NOT NULL DEFAULT 1,
    "vaccine_id" BIGINT,
    "injection_date" DATE,
    "actual_injection_date" DATE,
    "price" NUMERIC(19, 2),
    "note" VARCHAR(255),
    "created_at" DATE,
    "created_by" BIGINT,
    "updated_at" DATE,
    "updated_by" BIGINT,
    "status" BIGINT,
    CONSTRAINT "fk_vaccine_record_vaccine" FOREIGN KEY ("vaccine_id") REFERENCES "vaccines" ("id"),
    CONSTRAINT "fk_vaccine_record_child_disease" FOREIGN KEY ("disease_id") REFERENCES "child_vaccine_diseases" ("id")
);

ALTER TABLE IF EXISTS "vaccine_record"
    DROP COLUMN IF EXISTS "location_id",
    DROP COLUMN IF EXISTS "package_id",
    DROP COLUMN IF EXISTS "package_structure_id";

ALTER TABLE "vaccine_record"
    ADD COLUMN IF NOT EXISTS "profile_id" BIGINT,
    ADD COLUMN IF NOT EXISTS "disease_id" BIGINT,
    ADD COLUMN IF NOT EXISTS "dose_order" INTEGER,
    ADD COLUMN IF NOT EXISTS "source" BIGINT DEFAULT 1,
    ADD COLUMN IF NOT EXISTS "vaccine_id" BIGINT,
    ADD COLUMN IF NOT EXISTS "injection_date" DATE,
    ADD COLUMN IF NOT EXISTS "actual_injection_date" DATE,
    ADD COLUMN IF NOT EXISTS "price" NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS "note" VARCHAR(255),
    ADD COLUMN IF NOT EXISTS "created_at" DATE,
    ADD COLUMN IF NOT EXISTS "created_by" BIGINT,
    ADD COLUMN IF NOT EXISTS "updated_at" DATE,
    ADD COLUMN IF NOT EXISTS "updated_by" BIGINT,
    ADD COLUMN IF NOT EXISTS "status" BIGINT;

UPDATE "vaccine_record" SET "source" = 1 WHERE "source" IS NULL;
ALTER TABLE "vaccine_record" ALTER COLUMN "source" SET DEFAULT 1;
ALTER TABLE "vaccine_record" ALTER COLUMN "source" SET NOT NULL;

-- changeset codex:031-vaccine-record-constraints splitStatements:false
-- validCheckSum: ANY
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_vaccine_record_vaccine') THEN
        ALTER TABLE "vaccine_record"
            ADD CONSTRAINT "fk_vaccine_record_vaccine" FOREIGN KEY ("vaccine_id") REFERENCES "vaccines" ("id");
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_vaccine_record_child_disease') THEN
        ALTER TABLE "vaccine_record"
            ADD CONSTRAINT "fk_vaccine_record_child_disease" FOREIGN KEY ("disease_id") REFERENCES "child_vaccine_diseases" ("id");
    END IF;
END $$;

-- changeset codex:031-vaccine-indexes
-- validCheckSum: ANY
CREATE INDEX IF NOT EXISTS "idx_vaccine_disease_coverage_vaccine_id" ON "vaccine_disease_coverage" ("vaccine_id");
CREATE INDEX IF NOT EXISTS "idx_vaccine_disease_coverage_disease_id" ON "vaccine_disease_coverage" ("disease_id");
CREATE INDEX IF NOT EXISTS "idx_child_disease_dose_disease_id" ON "child_disease_dose_schedules" ("disease_id");
CREATE INDEX IF NOT EXISTS "idx_child_disease_dose_option_disease_id" ON "child_disease_dose_vaccine_options" ("disease_id");
CREATE INDEX IF NOT EXISTS "idx_child_disease_dose_option_vaccine_id" ON "child_disease_dose_vaccine_options" ("vaccine_id");
CREATE INDEX IF NOT EXISTS "idx_profile_vaccine_disease_status_profile_id" ON "profile_vaccine_disease_status" ("profile_id");
CREATE INDEX IF NOT EXISTS "idx_profile_vaccine_disease_status_disease_id" ON "profile_vaccine_disease_status" ("disease_id");
CREATE INDEX IF NOT EXISTS "idx_profile_vaccine_disease_status_status" ON "profile_vaccine_disease_status" ("status");
CREATE INDEX IF NOT EXISTS "idx_vaccine_record_profile_status" ON "vaccine_record" ("profile_id", "status");
CREATE INDEX IF NOT EXISTS "idx_vaccine_record_profile_disease_dose" ON "vaccine_record" ("profile_id", "disease_id", "dose_order");

-- changeset codex:031-vaccine-products
-- validCheckSum: ANY
INSERT INTO "vaccines" ("id", "name", "manufacturer", "origin", "description", "status", "created_at")
VALUES
    (1, 'Hexaxim', 'Sanofi', 'Pháp', '6 trong 1: bạch hầu, ho gà, uốn ván, bại liệt, Hib, viêm gan B.', 2, CURRENT_TIMESTAMP),
    (2, 'Rotarix', 'GSK', 'Bỉ', 'Phòng tiêu chảy cấp do Rotavirus.', 2, CURRENT_TIMESTAMP),
    (3, 'Varilrix', 'GSK', 'Bỉ', 'Phòng thủy đậu.', 2, CURRENT_TIMESTAMP),
    (4, 'Vaxigrip Tetra', 'Sanofi', 'Pháp', 'Phòng cúm mùa.', 2, CURRENT_TIMESTAMP),
    (5, 'MMR II', 'MSD', 'Mỹ', 'Phòng sởi, quai bị, rubella.', 2, CURRENT_TIMESTAMP),
    (6, 'Rotateq', 'MSD', 'Mỹ', 'Phòng tiêu chảy cấp do Rotavirus.', 2, CURRENT_TIMESTAMP),
    (7, 'Infanrix Hexa', 'GSK', 'Bỉ', '6 trong 1: bạch hầu, ho gà, uốn ván, bại liệt, Hib, viêm gan B.', 2, CURRENT_TIMESTAMP),
    (8, 'Prevenar 20', 'Pfizer', 'Bỉ', 'Phòng các bệnh do phế cầu khuẩn.', 2, CURRENT_TIMESTAMP),
    (9, 'Bexsero', 'GSK', 'Ý', 'Phòng não mô cầu nhóm B.', 2, CURRENT_TIMESTAMP),
    (10, 'MenQuadfi', 'Sanofi', 'Mỹ', 'Phòng não mô cầu A, C, Y, W-135.', 2, CURRENT_TIMESTAMP),
    (11, 'Nimenrix', 'Pfizer', 'Bỉ', 'Phòng não mô cầu A, C, Y, W-135.', 2, CURRENT_TIMESTAMP),
    (12, 'MVVac', 'Polyvac', 'Việt Nam', 'Phòng sởi.', 2, CURRENT_TIMESTAMP),
    (13, 'Imojev', 'Sanofi', 'Thái Lan', 'Phòng viêm não Nhật Bản.', 2, CURRENT_TIMESTAMP),
    (14, 'Priorix', 'GSK', 'Bỉ', 'Phòng sởi, quai bị, rubella.', 2, CURRENT_TIMESTAMP),
    (15, 'Twinrix', 'GSK', 'Bỉ', 'Phòng viêm gan A và viêm gan B.', 2, CURRENT_TIMESTAMP),
    (16, 'Typhoid Vi', 'Davac', 'Việt Nam', 'Phòng thương hàn.', 2, CURRENT_TIMESTAMP),
    (17, 'mOrcvax', 'Vabiotech', 'Việt Nam', 'Phòng bệnh tả.', 2, CURRENT_TIMESTAMP),
    (18, 'Varivax', 'MSD', 'Mỹ', 'Phòng thủy đậu.', 2, CURRENT_TIMESTAMP),
    (19, 'ProQuad', 'MSD', 'Mỹ', 'Phòng sởi, quai bị, rubella, thủy đậu.', 2, CURRENT_TIMESTAMP),
    (20, 'Avaxim 80U/0.5ml', 'Sanofi', 'Pháp', 'Phòng viêm gan A cho trẻ em.', 2, CURRENT_TIMESTAMP),
    (21, 'BCG', 'Việt Nam', 'Việt Nam', 'Phòng lao cho trẻ sơ sinh.', 2, CURRENT_TIMESTAMP),
    (22, 'Vắc xin viêm gan B sơ sinh', 'Nhiều hãng', 'Nhiều nước', 'Phòng viêm gan B trong 24 giờ đầu sau sinh.', 2, CURRENT_TIMESTAMP),
    (23, 'Synflorix', 'GSK', 'Bỉ', 'Phòng các bệnh do phế cầu khuẩn.', 2, CURRENT_TIMESTAMP),
    (24, 'Prevenar 13', 'Pfizer', 'Bỉ', 'Phòng các bệnh do phế cầu khuẩn.', 2, CURRENT_TIMESTAMP),
    (25, 'Vaxneuvance', 'MSD', 'Mỹ', 'Phòng các bệnh do phế cầu khuẩn.', 2, CURRENT_TIMESTAMP),
    (26, 'VA-MENGOC-BC', 'Finlay', 'Cuba', 'Phòng não mô cầu nhóm B và C.', 2, CURRENT_TIMESTAMP),
    (27, 'Menactra', 'Sanofi', 'Mỹ', 'Phòng não mô cầu A, C, Y, W-135.', 2, CURRENT_TIMESTAMP),
    (28, 'Jevax', 'Vabiotech', 'Việt Nam', 'Phòng viêm não Nhật Bản.', 2, CURRENT_TIMESTAMP),
    (29, 'Pneumovax 23', 'MSD', 'Mỹ', 'Phòng các bệnh do phế cầu khuẩn.', 2, CURRENT_TIMESTAMP),
    (30, 'Pentaxim', 'Sanofi', 'Pháp', 'Vắc-xin 5 trong 1 phòng bạch hầu, ho gà, uốn ván, bại liệt và Hib.', 2, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO UPDATE SET
    "name" = EXCLUDED."name",
    "manufacturer" = EXCLUDED."manufacturer",
    "origin" = EXCLUDED."origin",
    "description" = EXCLUDED."description",
    "status" = EXCLUDED."status",
    "updated_at" = CURRENT_TIMESTAMP;

SELECT setval(pg_get_serial_sequence('"vaccines"', 'id'), COALESCE((SELECT MAX("id") FROM "vaccines"), 1), true);

-- changeset codex:031-vaccine-diseases-and-schedules
-- validCheckSum: ANY
INSERT INTO "child_vaccine_diseases" ("code", "name", "description", "is_required", "display_order", "status", "created_at")
VALUES
    ('TUBERCULOSIS', 'Lao', 'Bệnh lao ở trẻ em.', TRUE, 1, 2, CURRENT_TIMESTAMP),
    ('HEPATITIS_B', 'Viêm gan B', 'Bệnh viêm gan B, gồm mũi sơ sinh và các mũi nhắc qua vắc-xin đơn hoặc phối hợp.', TRUE, 2, 2, CURRENT_TIMESTAMP),
    ('DIPHTHERIA', 'Bạch hầu', 'Bệnh bạch hầu, thường được phòng bằng vắc-xin phối hợp 5 trong 1 hoặc 6 trong 1.', TRUE, 3, 2, CURRENT_TIMESTAMP),
    ('PERTUSSIS', 'Ho gà', 'Bệnh ho gà, thường được phòng bằng vắc-xin phối hợp 5 trong 1 hoặc 6 trong 1.', TRUE, 4, 2, CURRENT_TIMESTAMP),
    ('TETANUS', 'Uốn ván', 'Bệnh uốn ván, thường được phòng bằng vắc-xin phối hợp 5 trong 1 hoặc 6 trong 1.', TRUE, 5, 2, CURRENT_TIMESTAMP),
    ('POLIO', 'Bại liệt', 'Bệnh bại liệt, có thể được phòng trong các vắc-xin phối hợp.', TRUE, 6, 2, CURRENT_TIMESTAMP),
    ('HIB', 'Hib', 'Các bệnh do Haemophilus influenzae type b.', TRUE, 7, 2, CURRENT_TIMESTAMP),
    ('ROTA', 'Tiêu chảy do Rota', 'Tiêu chảy cấp do Rotavirus.', TRUE, 8, 2, CURRENT_TIMESTAMP),
    ('PNEUMOCOCCAL', 'Phế cầu', 'Các bệnh do phế cầu khuẩn.', TRUE, 9, 2, CURRENT_TIMESTAMP),
    ('MENINGOCOCCAL_B', 'Não mô cầu nhóm B', 'Bệnh do não mô cầu nhóm B.', TRUE, 10, 2, CURRENT_TIMESTAMP),
    ('MENINGOCOCCAL_ACYW', 'Não mô cầu A, C, Y, W-135', 'Bệnh do não mô cầu các nhóm A, C, Y, W-135.', TRUE, 11, 2, CURRENT_TIMESTAMP),
    ('INFLUENZA', 'Cúm', 'Cúm mùa.', TRUE, 12, 2, CURRENT_TIMESTAMP),
    ('MEASLES', 'Sởi', 'Bệnh sởi.', TRUE, 13, 2, CURRENT_TIMESTAMP),
    ('MUMPS', 'Quai bị', 'Bệnh quai bị.', TRUE, 14, 2, CURRENT_TIMESTAMP),
    ('RUBELLA', 'Rubella', 'Bệnh rubella.', TRUE, 15, 2, CURRENT_TIMESTAMP),
    ('VARICELLA', 'Thủy đậu', 'Bệnh thủy đậu.', TRUE, 16, 2, CURRENT_TIMESTAMP),
    ('JAPANESE_ENCEPHALITIS', 'Viêm não Nhật Bản', 'Bệnh viêm não Nhật Bản.', TRUE, 17, 2, CURRENT_TIMESTAMP),
    ('HEPATITIS_A', 'Viêm gan A', 'Bệnh viêm gan A.', TRUE, 18, 2, CURRENT_TIMESTAMP),
    ('TYPHOID', 'Thương hàn', 'Bệnh thương hàn.', FALSE, 19, 2, CURRENT_TIMESTAMP),
    ('CHOLERA', 'Tả', 'Bệnh tả.', FALSE, 20, 2, CURRENT_TIMESTAMP)
ON CONFLICT ("code") DO UPDATE SET
    "name" = EXCLUDED."name",
    "description" = EXCLUDED."description",
    "is_required" = EXCLUDED."is_required",
    "display_order" = EXCLUDED."display_order",
    "status" = EXCLUDED."status",
    "updated_at" = CURRENT_TIMESTAMP;

CREATE TEMP TABLE "child_disease_seed_doses" (
    "disease_code" VARCHAR(100),
    "dose_order" INTEGER,
    "recommended_age_months" INTEGER,
    "interval_days" INTEGER,
    "dose_label" VARCHAR(255),
    "note" TEXT
) ON COMMIT DROP;

INSERT INTO "child_disease_seed_doses" ("disease_code", "dose_order", "recommended_age_months", "interval_days", "dose_label", "note")
VALUES
    ('TUBERCULOSIS', 1, 0, NULL, 'Mũi 1', 'Tiêm càng sớm càng tốt sau sinh.'),
    ('HEPATITIS_B', 1, 0, NULL, 'Mũi sơ sinh', 'Tiêm trong 24 giờ đầu sau sinh nếu đủ điều kiện.'),
    ('HEPATITIS_B', 2, 2, 30, 'Mũi 2', 'Có thể được phủ bởi vắc-xin 6 trong 1.'),
    ('HEPATITIS_B', 3, 3, 30, 'Mũi 3', 'Có thể được phủ bởi vắc-xin 5 trong 1 hoặc 6 trong 1 phù hợp.'),
    ('HEPATITIS_B', 4, 4, 30, 'Mũi 4', 'Có thể được phủ bởi vắc-xin 6 trong 1.'),
    ('DIPHTHERIA', 1, 2, NULL, 'Mũi 1', NULL),
    ('DIPHTHERIA', 2, 3, 30, 'Mũi 2', NULL),
    ('DIPHTHERIA', 3, 4, 30, 'Mũi 3', NULL),
    ('DIPHTHERIA', 4, 18, 365, 'Mũi nhắc', NULL),
    ('PERTUSSIS', 1, 2, NULL, 'Mũi 1', NULL),
    ('PERTUSSIS', 2, 3, 30, 'Mũi 2', NULL),
    ('PERTUSSIS', 3, 4, 30, 'Mũi 3', NULL),
    ('PERTUSSIS', 4, 18, 365, 'Mũi nhắc', NULL),
    ('TETANUS', 1, 2, NULL, 'Mũi 1', NULL),
    ('TETANUS', 2, 3, 30, 'Mũi 2', NULL),
    ('TETANUS', 3, 4, 30, 'Mũi 3', NULL),
    ('TETANUS', 4, 18, 365, 'Mũi nhắc', NULL),
    ('POLIO', 1, 2, NULL, 'Mũi 1', NULL),
    ('POLIO', 2, 3, 30, 'Mũi 2', NULL),
    ('POLIO', 3, 4, 30, 'Mũi 3', NULL),
    ('POLIO', 4, 18, 365, 'Mũi nhắc', NULL),
    ('HIB', 1, 2, NULL, 'Mũi 1', NULL),
    ('HIB', 2, 3, 30, 'Mũi 2', NULL),
    ('HIB', 3, 4, 30, 'Mũi 3', NULL),
    ('HIB', 4, 18, 365, 'Mũi nhắc', NULL),
    ('ROTA', 1, 2, NULL, 'Liều 1', 'Hoàn thành sớm theo giới hạn tuổi của sản phẩm.'),
    ('ROTA', 2, 3, 30, 'Liều 2', NULL),
    ('ROTA', 3, 4, 30, 'Liều 3', 'Áp dụng khi dùng phác đồ 3 liều.'),
    ('PNEUMOCOCCAL', 1, 2, NULL, 'Mũi 1', NULL),
    ('PNEUMOCOCCAL', 2, 3, 30, 'Mũi 2', NULL),
    ('PNEUMOCOCCAL', 3, 4, 30, 'Mũi 3', NULL),
    ('PNEUMOCOCCAL', 4, 12, 240, 'Mũi nhắc', NULL),
    ('MENINGOCOCCAL_B', 1, 2, NULL, 'Mũi 1', NULL),
    ('MENINGOCOCCAL_B', 2, 4, 60, 'Mũi 2', NULL),
    ('MENINGOCOCCAL_B', 3, 12, 180, 'Mũi nhắc', NULL),
    ('MENINGOCOCCAL_ACYW', 1, 9, NULL, 'Mũi 1', NULL),
    ('MENINGOCOCCAL_ACYW', 2, 12, 90, 'Mũi 2', NULL),
    ('INFLUENZA', 1, 6, NULL, 'Mũi 1', 'Tiêm nhắc hằng năm.'),
    ('INFLUENZA', 2, 7, 30, 'Mũi 2 mùa đầu', 'Áp dụng với trẻ tiêm cúm lần đầu theo chỉ định.'),
    ('MEASLES', 1, 9, NULL, 'Mũi 1', NULL),
    ('MEASLES', 2, 18, 270, 'Mũi 2', 'Có thể được phủ bởi MMR hoặc MMRV.'),
    ('MUMPS', 1, 12, NULL, 'Mũi 1', 'Thường được phủ bởi MMR hoặc MMRV.'),
    ('MUMPS', 2, 18, 180, 'Mũi 2', NULL),
    ('RUBELLA', 1, 12, NULL, 'Mũi 1', 'Thường được phủ bởi MMR hoặc MMRV.'),
    ('RUBELLA', 2, 18, 180, 'Mũi 2', NULL),
    ('VARICELLA', 1, 12, NULL, 'Mũi 1', NULL),
    ('VARICELLA', 2, 48, 90, 'Mũi 2', NULL),
    ('JAPANESE_ENCEPHALITIS', 1, 9, NULL, 'Mũi 1', 'Không tự ý hoán đổi Jevax và Imojev.'),
    ('JAPANESE_ENCEPHALITIS', 2, 12, 365, 'Mũi 2', NULL),
    ('HEPATITIS_A', 1, 12, NULL, 'Mũi 1', NULL),
    ('HEPATITIS_A', 2, 18, 180, 'Mũi 2', NULL),
    ('TYPHOID', 1, 24, NULL, 'Mũi 1', NULL),
    ('CHOLERA', 1, 24, NULL, 'Liều 1', NULL),
    ('CHOLERA', 2, 24, 14, 'Liều 2', NULL);

INSERT INTO "child_disease_dose_schedules" ("disease_id", "dose_order", "recommended_age_months", "interval_days", "dose_label", "note", "status", "created_at")
SELECT d."id", s."dose_order", s."recommended_age_months", s."interval_days", s."dose_label", s."note", 2, CURRENT_TIMESTAMP
FROM "child_disease_seed_doses" s
JOIN "child_vaccine_diseases" d ON d."code" = s."disease_code"
ON CONFLICT ("disease_id", "dose_order") DO UPDATE SET
    "recommended_age_months" = EXCLUDED."recommended_age_months",
    "interval_days" = EXCLUDED."interval_days",
    "dose_label" = EXCLUDED."dose_label",
    "note" = EXCLUDED."note",
    "status" = EXCLUDED."status",
    "updated_at" = CURRENT_TIMESTAMP;

-- changeset codex:031-vaccine-disease-coverage
-- validCheckSum: ANY
CREATE TEMP TABLE "vaccine_disease_seed_coverage" (
    "vaccine_id" BIGINT,
    "disease_code" VARCHAR(100),
    "product_family_code" VARCHAR(100),
    "interchange_rule" BIGINT
) ON COMMIT DROP;

INSERT INTO "vaccine_disease_seed_coverage" ("vaccine_id", "disease_code", "product_family_code", "interchange_rule")
VALUES
    (1, 'DIPHTHERIA', 'HEXAVALENT', 1), (1, 'PERTUSSIS', 'HEXAVALENT', 1), (1, 'TETANUS', 'HEXAVALENT', 1),
    (1, 'POLIO', 'HEXAVALENT', 1), (1, 'HIB', 'HEXAVALENT', 1), (1, 'HEPATITIS_B', 'HEXAVALENT', 1),
    (7, 'DIPHTHERIA', 'HEXAVALENT', 1), (7, 'PERTUSSIS', 'HEXAVALENT', 1), (7, 'TETANUS', 'HEXAVALENT', 1),
    (7, 'POLIO', 'HEXAVALENT', 1), (7, 'HIB', 'HEXAVALENT', 1), (7, 'HEPATITIS_B', 'HEXAVALENT', 1),
    (30, 'DIPHTHERIA', 'PENTAVALENT_DTP_IPV_HIB', 1), (30, 'PERTUSSIS', 'PENTAVALENT_DTP_IPV_HIB', 1),
    (30, 'TETANUS', 'PENTAVALENT_DTP_IPV_HIB', 1), (30, 'POLIO', 'PENTAVALENT_DTP_IPV_HIB', 1), (30, 'HIB', 'PENTAVALENT_DTP_IPV_HIB', 1),
    (22, 'HEPATITIS_B', 'HEPB_BIRTH', 2),
    (15, 'HEPATITIS_A', 'HEPA_HEPB_COMBO', 2), (15, 'HEPATITIS_B', 'HEPA_HEPB_COMBO', 2),
    (2, 'ROTA', 'RV1_ROTARIX', 2), (6, 'ROTA', 'RV5_ROTATEQ', 3),
    (8, 'PNEUMOCOCCAL', 'PCV20', 1), (23, 'PNEUMOCOCCAL', 'PCV10', 1), (24, 'PNEUMOCOCCAL', 'PCV13', 1),
    (25, 'PNEUMOCOCCAL', 'PCV15', 1), (29, 'PNEUMOCOCCAL', 'PPSV23', 2),
    (9, 'MENINGOCOCCAL_B', 'MENB_BEXSERO', 2), (26, 'MENINGOCOCCAL_B', 'MENBC', 2),
    (10, 'MENINGOCOCCAL_ACYW', 'MENACYW', 1), (11, 'MENINGOCOCCAL_ACYW', 'MENACYW', 1), (27, 'MENINGOCOCCAL_ACYW', 'MENACYW', 1),
    (4, 'INFLUENZA', 'FLU_TETRA', 6),
    (12, 'MEASLES', 'MEASLES_SINGLE', 2),
    (5, 'MEASLES', 'MMR', 1), (5, 'MUMPS', 'MMR', 1), (5, 'RUBELLA', 'MMR', 1),
    (14, 'MEASLES', 'MMR', 1), (14, 'MUMPS', 'MMR', 1), (14, 'RUBELLA', 'MMR', 1),
    (19, 'MEASLES', 'MMRV_COMBO', 1), (19, 'MUMPS', 'MMRV_COMBO', 1), (19, 'RUBELLA', 'MMRV_COMBO', 1), (19, 'VARICELLA', 'MMRV_COMBO', 1),
    (3, 'VARICELLA', 'VARICELLA', 1), (18, 'VARICELLA', 'VARICELLA', 1),
    (13, 'JAPANESE_ENCEPHALITIS', 'LIVE_IMOJEV', 4), (28, 'JAPANESE_ENCEPHALITIS', 'INACTIVATED_JEVAX', 4),
    (20, 'HEPATITIS_A', 'HEPATITIS_A', 1),
    (16, 'TYPHOID', 'TYPHOID_VI', 2),
    (17, 'CHOLERA', 'ORAL_CHOLERA', 2),
    (21, 'TUBERCULOSIS', 'BCG', 2);

INSERT INTO "vaccine_disease_coverage" ("vaccine_id", "disease_id", "product_family_code", "interchange_rule", "status", "created_at")
SELECT s."vaccine_id", d."id", s."product_family_code", s."interchange_rule", 2, CURRENT_TIMESTAMP
FROM "vaccine_disease_seed_coverage" s
JOIN "vaccines" v ON v."id" = s."vaccine_id"
JOIN "child_vaccine_diseases" d ON d."code" = s."disease_code"
ON CONFLICT ("vaccine_id", "disease_id") DO UPDATE SET
    "product_family_code" = EXCLUDED."product_family_code",
    "interchange_rule" = EXCLUDED."interchange_rule",
    "status" = EXCLUDED."status",
    "updated_at" = CURRENT_TIMESTAMP;

-- changeset codex:031-vaccine-dose-options
-- validCheckSum: ANY
INSERT INTO "child_disease_dose_vaccine_options" (
    "disease_id", "dose_schedule_id", "dose_order", "vaccine_id",
    "is_preferred", "display_order", "note", "status", "created_at"
)
SELECT
    s."disease_id",
    s."id",
    s."dose_order",
    c."vaccine_id",
    FALSE,
    ROW_NUMBER() OVER (PARTITION BY s."disease_id", s."dose_order" ORDER BY c."product_family_code", c."vaccine_id"),
    NULL,
    2,
    CURRENT_TIMESTAMP
FROM "child_disease_dose_schedules" s
JOIN "vaccine_disease_coverage" c ON c."disease_id" = s."disease_id" AND c."status" = 2
JOIN "vaccines" v ON v."id" = c."vaccine_id" AND v."status" = 2
WHERE s."status" = 2
ON CONFLICT ("disease_id", "dose_order", "vaccine_id") DO UPDATE SET
    "dose_schedule_id" = EXCLUDED."dose_schedule_id",
    "display_order" = EXCLUDED."display_order",
    "status" = EXCLUDED."status",
    "updated_at" = CURRENT_TIMESTAMP;

UPDATE "child_disease_dose_vaccine_options" o
SET "status" = 0, "updated_at" = CURRENT_TIMESTAMP
FROM "child_vaccine_diseases" d
WHERE o."disease_id" = d."id"
  AND d."code" = 'HEPATITIS_B'
  AND o."dose_order" = 1
  AND o."vaccine_id" <> 22;

UPDATE "child_disease_dose_vaccine_options" o
SET "is_preferred" = TRUE,
    "display_order" = 1,
    "note" = 'Mũi viêm gan B sơ sinh trong 24 giờ đầu sau sinh nếu đủ điều kiện.',
    "status" = 2,
    "updated_at" = CURRENT_TIMESTAMP
FROM "child_vaccine_diseases" d
WHERE o."disease_id" = d."id"
  AND d."code" = 'HEPATITIS_B'
  AND o."dose_order" = 1
  AND o."vaccine_id" = 22;

UPDATE "child_disease_dose_vaccine_options" o
SET "is_preferred" = TRUE,
    "note" = 'Có thể dùng vaccine 6 trong 1 cho các mũi sau sơ sinh theo lịch.',
    "updated_at" = CURRENT_TIMESTAMP
FROM "child_vaccine_diseases" d
WHERE o."disease_id" = d."id"
  AND d."code" = 'HEPATITIS_B'
  AND o."dose_order" IN (2, 3, 4)
  AND o."vaccine_id" IN (1, 7);

UPDATE "child_disease_dose_vaccine_options" o
SET "is_preferred" = TRUE,
    "note" = 'Vaccine 5 trong 1 phù hợp cho bạch hầu, ho gà, uốn ván, bại liệt và Hib; không thay thế mũi viêm gan B.',
    "updated_at" = CURRENT_TIMESTAMP
FROM "child_vaccine_diseases" d
WHERE o."disease_id" = d."id"
  AND d."code" IN ('DIPHTHERIA', 'PERTUSSIS', 'TETANUS', 'POLIO', 'HIB')
  AND o."vaccine_id" = 30;

SELECT setval(pg_get_serial_sequence('"child_vaccine_diseases"', 'id'), COALESCE((SELECT MAX("id") FROM "child_vaccine_diseases"), 1), true);
SELECT setval(pg_get_serial_sequence('"vaccine_disease_coverage"', 'id'), COALESCE((SELECT MAX("id") FROM "vaccine_disease_coverage"), 1), true);
SELECT setval(pg_get_serial_sequence('"child_disease_dose_schedules"', 'id'), COALESCE((SELECT MAX("id") FROM "child_disease_dose_schedules"), 1), true);
SELECT setval(pg_get_serial_sequence('"child_disease_dose_vaccine_options"', 'id'), COALESCE((SELECT MAX("id") FROM "child_disease_dose_vaccine_options"), 1), true);

-- changeset codex:031-vaccine-demo-records
-- validCheckSum: ANY
UPDATE "profile"
SET
    "name" = CASE
        WHEN "id" = 1 THEN 'Bé Thảo Nhật'
        WHEN "id" = 2 THEN 'Bé Thảo Hai'
        ELSE "name"
    END,
    "date_of_birth" = CASE
        WHEN "id" = 1 THEN DATE '2025-06-09'
        WHEN "id" = 2 THEN DATE '2026-02-09'
        ELSE "date_of_birth"
    END,
    "updated_at" = CURRENT_TIMESTAMP,
    "updated_by" = 'SYSTEM'
WHERE "id" IN (1, 2);

DELETE FROM "vaccine_record"
WHERE "id" IN (1, 2, 3);

WITH seed (
    "id", "profile_id", "vaccine_id", "injection_date", "actual_injection_date", "status"
) AS (
    VALUES
        (1001::BIGINT, 1::BIGINT, 1::BIGINT, DATE '2025-08-09', DATE '2025-08-09', 3::BIGINT),
        (1002::BIGINT, 1::BIGINT, 1::BIGINT, DATE '2025-09-09', DATE '2025-09-09', 3::BIGINT),
        (1003::BIGINT, 1::BIGINT, 1::BIGINT, DATE '2025-10-09', DATE '2025-10-09', 3::BIGINT),
        (1004::BIGINT, 1::BIGINT, 2::BIGINT, DATE '2025-07-23', DATE '2025-07-23', 3::BIGINT),
        (1005::BIGINT, 1::BIGINT, 2::BIGINT, DATE '2025-09-09', DATE '2025-09-09', 3::BIGINT),
        (1006::BIGINT, 1::BIGINT, 8::BIGINT, DATE '2025-07-23', DATE '2025-07-23', 3::BIGINT),
        (1007::BIGINT, 1::BIGINT, 8::BIGINT, DATE '2025-09-09', DATE '2025-09-09', 3::BIGINT),
        (1008::BIGINT, 1::BIGINT, 8::BIGINT, DATE '2025-10-09', DATE '2025-10-09', 3::BIGINT),
        (1009::BIGINT, 1::BIGINT, 9::BIGINT, DATE '2025-08-09', DATE '2025-08-09', 3::BIGINT),
        (1010::BIGINT, 1::BIGINT, 9::BIGINT, DATE '2025-10-09', DATE '2025-10-09', 3::BIGINT),
        (1011::BIGINT, 1::BIGINT, 10::BIGINT, DATE '2025-07-23', DATE '2025-07-23', 3::BIGINT),
        (1012::BIGINT, 1::BIGINT, 10::BIGINT, DATE '2025-10-09', DATE '2025-10-09', 3::BIGINT),
        (1013::BIGINT, 1::BIGINT, 4::BIGINT, DATE '2025-12-09', DATE '2025-12-09', 3::BIGINT),
        (1014::BIGINT, 1::BIGINT, 12::BIGINT, DATE '2026-03-09', DATE '2026-03-09', 3::BIGINT),
        (1015::BIGINT, 1::BIGINT, 13::BIGINT, DATE '2026-03-09', DATE '2026-03-09', 3::BIGINT),
        (1016::BIGINT, 1::BIGINT, 3::BIGINT, DATE '2026-03-09', DATE '2026-03-09', 3::BIGINT),
        (1017::BIGINT, 1::BIGINT, 14::BIGINT, DATE '2026-03-09', DATE '2026-03-09', 3::BIGINT),
        (1018::BIGINT, 1::BIGINT, 8::BIGINT, DATE '2026-06-09', NULL::DATE, -1::BIGINT),
        (1019::BIGINT, 1::BIGINT, 9::BIGINT, DATE '2026-06-09', NULL::DATE, -1::BIGINT),
        (1020::BIGINT, 1::BIGINT, 3::BIGINT, DATE '2026-06-09', NULL::DATE, -1::BIGINT),
        (1021::BIGINT, 1::BIGINT, 15::BIGINT, DATE '2026-06-09', NULL::DATE, -1::BIGINT),
        (1022::BIGINT, 1::BIGINT, 20::BIGINT, DATE '2026-06-09', NULL::DATE, -1::BIGINT),
        (1023::BIGINT, 1::BIGINT, 1::BIGINT, DATE '2026-12-09', NULL::DATE, -1::BIGINT),
        (2001::BIGINT, 2::BIGINT, 2::BIGINT, DATE '2026-03-23', DATE '2026-03-23', 3::BIGINT),
        (2002::BIGINT, 2::BIGINT, 2::BIGINT, DATE '2026-05-09', DATE '2026-05-09', 3::BIGINT),
        (2003::BIGINT, 2::BIGINT, 1::BIGINT, DATE '2026-04-09', DATE '2026-04-09', 3::BIGINT),
        (2004::BIGINT, 2::BIGINT, 1::BIGINT, DATE '2026-05-09', DATE '2026-05-09', 3::BIGINT),
        (2005::BIGINT, 2::BIGINT, 8::BIGINT, DATE '2026-03-23', DATE '2026-03-23', 3::BIGINT),
        (2006::BIGINT, 2::BIGINT, 8::BIGINT, DATE '2026-05-09', DATE '2026-05-09', 3::BIGINT),
        (2007::BIGINT, 2::BIGINT, 9::BIGINT, DATE '2026-04-09', DATE '2026-04-09', 3::BIGINT),
        (2008::BIGINT, 2::BIGINT, 10::BIGINT, DATE '2026-03-23', DATE '2026-03-23', 3::BIGINT),
        (2009::BIGINT, 2::BIGINT, 1::BIGINT, DATE '2026-06-09', NULL::DATE, -1::BIGINT),
        (2010::BIGINT, 2::BIGINT, 8::BIGINT, DATE '2026-06-09', NULL::DATE, -1::BIGINT),
        (2011::BIGINT, 2::BIGINT, 9::BIGINT, DATE '2026-06-09', NULL::DATE, -1::BIGINT),
        (2012::BIGINT, 2::BIGINT, 10::BIGINT, DATE '2026-06-09', NULL::DATE, -1::BIGINT),
        (2013::BIGINT, 2::BIGINT, 4::BIGINT, DATE '2026-08-09', NULL::DATE, -1::BIGINT)
),
seed_with_note AS (
    SELECT
        s.*,
        CASE
            WHEN s."id" = 1023 THEN 'Hồ sơ 1 - mốc 18 tháng: mũi tiêm sắp tới, dữ liệu demo mới lẻ'
            WHEN s."id" = 2013 THEN 'Hồ sơ 2 - mốc 6 tháng: mũi tiêm sắp tới, dữ liệu demo mới lẻ'
            WHEN s."profile_id" = 1 AND s."status" = 3 THEN 'Hồ sơ 1 - bé 12 tháng: mũi đã tiêm theo lịch, dữ liệu demo mới lẻ'
            WHEN s."profile_id" = 1 AND s."status" = -1 THEN 'Hồ sơ 1 - bé 12 tháng: mũi tiêm đến hạn, dữ liệu demo mới lẻ'
            WHEN s."profile_id" = 2 AND s."status" = 3 THEN 'Hồ sơ 2 - bé 4 tháng: mũi đã tiêm theo lịch, dữ liệu demo mới lẻ'
            ELSE 'Hồ sơ 2 - bé 4 tháng: mũi tiêm đến hạn, dữ liệu demo mới lẻ'
        END AS "note"
    FROM seed s
)
INSERT INTO "vaccine_record" (
    "id", "profile_id", "disease_id", "dose_order", "source", "vaccine_id",
    "injection_date", "actual_injection_date", "price", "note",
    "created_at", "created_by", "status"
)
SELECT
    "id",
    "profile_id",
    NULL::BIGINT,
    NULL::INTEGER,
    1::BIGINT,
    "vaccine_id",
    "injection_date",
    "actual_injection_date",
    0.00,
    "note",
    CURRENT_DATE,
    1,
    "status"
FROM seed_with_note
ON CONFLICT ("id") DO UPDATE SET
    "profile_id" = EXCLUDED."profile_id",
    "disease_id" = EXCLUDED."disease_id",
    "dose_order" = EXCLUDED."dose_order",
    "source" = EXCLUDED."source",
    "vaccine_id" = EXCLUDED."vaccine_id",
    "injection_date" = EXCLUDED."injection_date",
    "actual_injection_date" = EXCLUDED."actual_injection_date",
    "price" = EXCLUDED."price",
    "note" = EXCLUDED."note",
    "status" = EXCLUDED."status",
    "updated_at" = CURRENT_DATE,
    "updated_by" = 1;

SELECT setval(pg_get_serial_sequence('"vaccine_record"', 'id'), COALESCE((SELECT MAX("id") FROM "vaccine_record"), 1), true);
