-- liquibase formatted sql

-- changeset codex:095
-- validCheckSum: ANY
DROP TABLE IF EXISTS "vaccine_record" CASCADE;
DROP TABLE IF EXISTS "vaccine_pricing" CASCADE;
DROP TABLE IF EXISTS "vaccine_schedule" CASCADE;
DROP TABLE IF EXISTS "vaccination_center" CASCADE;
DROP TABLE IF EXISTS "vaccine_type" CASCADE;

-- changeset codex:096
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "locations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "region" VARCHAR(255),
    "address" VARCHAR(255),
    "status" BIGINT,
    "created_at" TIMESTAMP(6),
    "updated_at" TIMESTAMP(6)
);

-- changeset codex:097
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "vaccines" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "manufacturer" VARCHAR(255),
    "origin" VARCHAR(255),
    "description" TEXT,
    "status" BIGINT,
    "created_at" TIMESTAMP(6),
    "updated_at" TIMESTAMP(6)
);

-- changeset codex:098
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "vaccine_packages" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code" VARCHAR(255) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "status" BIGINT,
    "created_at" TIMESTAMP(6),
    "updated_at" TIMESTAMP(6),
    CONSTRAINT "uk_vaccine_packages_code" UNIQUE ("code")
);

-- changeset codex:099
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "package_structures" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "package_id" BIGINT NOT NULL,
    "duration_months" INTEGER NOT NULL,
    "vaccine_id" BIGINT NOT NULL,
    "recommended_age_months" INTEGER NOT NULL,
    "dosage_order" INTEGER NOT NULL,
    "dose_label" VARCHAR(255),
    "note" TEXT,
    CONSTRAINT "fk_package_structures_package"
        FOREIGN KEY ("package_id") REFERENCES "vaccine_packages" ("id"),
    CONSTRAINT "fk_package_structures_vaccine"
        FOREIGN KEY ("vaccine_id") REFERENCES "vaccines" ("id"),
    CONSTRAINT "uk_package_structures_order"
        UNIQUE ("package_id", "duration_months", "vaccine_id", "recommended_age_months", "dosage_order")
);

-- changeset codex:100
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "location_vaccine_prices" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "location_id" BIGINT NOT NULL,
    "vaccine_id" BIGINT NOT NULL,
    "retail_price" NUMERIC(19, 2) NOT NULL,
    "stock_status" BOOLEAN,
    "status" BIGINT,
    "created_at" TIMESTAMP(6),
    "updated_at" TIMESTAMP(6),
    CONSTRAINT "fk_location_vaccine_prices_location"
        FOREIGN KEY ("location_id") REFERENCES "locations" ("id"),
    CONSTRAINT "fk_location_vaccine_prices_vaccine"
        FOREIGN KEY ("vaccine_id") REFERENCES "vaccines" ("id"),
    CONSTRAINT "uk_location_vaccine_prices"
        UNIQUE ("location_id", "vaccine_id")
);

-- changeset codex:101
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "location_package_prices" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "location_id" BIGINT NOT NULL,
    "package_id" BIGINT NOT NULL,
    "duration_months" INTEGER NOT NULL,
    "base_vaccine_sum" NUMERIC(19, 2),
    "service_fee" NUMERIC(19, 2),
    "discount_amount" NUMERIC(19, 2),
    "final_package_price" NUMERIC(19, 2) NOT NULL,
    "gift_description" TEXT,
    "created_at" TIMESTAMP(6),
    "updated_at" TIMESTAMP(6),
    CONSTRAINT "fk_location_package_prices_location"
        FOREIGN KEY ("location_id") REFERENCES "locations" ("id"),
    CONSTRAINT "fk_location_package_prices_package"
        FOREIGN KEY ("package_id") REFERENCES "vaccine_packages" ("id"),
    CONSTRAINT "uk_location_package_prices"
        UNIQUE ("location_id", "package_id", "duration_months")
);

-- changeset codex:102
-- validCheckSum: ANY
CREATE TABLE IF NOT EXISTS "vaccine_record" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "profile_id" BIGINT,
    "location_id" BIGINT,
    "vaccine_id" BIGINT,
    "package_id" BIGINT,
    "package_structure_id" BIGINT,
    "injection_date" DATE,
    "actual_injection_date" DATE,
    "price" NUMERIC(19, 2),
    "note" VARCHAR(255),
    "created_at" DATE,
    "created_by" BIGINT,
    "updated_at" DATE,
    "updated_by" BIGINT,
    "status" BIGINT,
    CONSTRAINT "fk_vaccine_record_location"
        FOREIGN KEY ("location_id") REFERENCES "locations" ("id"),
    CONSTRAINT "fk_vaccine_record_vaccine"
        FOREIGN KEY ("vaccine_id") REFERENCES "vaccines" ("id"),
    CONSTRAINT "fk_vaccine_record_package"
        FOREIGN KEY ("package_id") REFERENCES "vaccine_packages" ("id"),
    CONSTRAINT "fk_vaccine_record_package_structure"
        FOREIGN KEY ("package_structure_id") REFERENCES "package_structures" ("id")
);

-- changeset codex:103
-- validCheckSum: ANY
CREATE INDEX IF NOT EXISTS "idx_package_structures_package_duration"
    ON "package_structures" ("package_id", "duration_months");

CREATE INDEX IF NOT EXISTS "idx_location_vaccine_prices_location"
    ON "location_vaccine_prices" ("location_id");

CREATE INDEX IF NOT EXISTS "idx_location_package_prices_location"
    ON "location_package_prices" ("location_id");

CREATE INDEX IF NOT EXISTS "idx_vaccine_record_profile_status"
    ON "vaccine_record" ("profile_id", "status");
