-- liquibase formatted sql

-- changeset codex:047-create-app-analytics
CREATE TABLE IF NOT EXISTS user_daily_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    activity_date DATE NOT NULL,
    first_active_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_daily_activity_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_user_daily_activity_user_date
        UNIQUE (user_id, activity_date)
);

CREATE INDEX IF NOT EXISTS idx_user_daily_activity_date
    ON user_daily_activity (activity_date);

-- changeset codex:048-create-app-page-daily-activity
CREATE TABLE IF NOT EXISTS app_page_daily_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    page_key VARCHAR(100) NOT NULL,
    activity_date DATE NOT NULL,
    view_count BIGINT NOT NULL DEFAULT 1,
    first_viewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_viewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_app_page_daily_activity_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_app_page_daily_activity_user_page_date
        UNIQUE (user_id, page_key, activity_date),
    CONSTRAINT ck_app_page_daily_activity_view_count
        CHECK (view_count > 0)
);

CREATE INDEX IF NOT EXISTS idx_app_page_daily_activity_page_date
    ON app_page_daily_activity (page_key, activity_date);
