-- liquibase formatted sql

-- changeset codex:049-create-user-daily-activity
CREATE TABLE IF NOT EXISTS "user_daily_activity" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "activity_date" DATE NOT NULL,
    "first_seen_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_seen_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "request_count" BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT "fk_user_daily_activity_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE,
    CONSTRAINT "uk_user_daily_activity_user_date" UNIQUE ("user_id", "activity_date")
);

-- changeset codex:049-index-user-daily-activity-date
CREATE INDEX IF NOT EXISTS "idx_user_daily_activity_date"
    ON "user_daily_activity" ("activity_date");

-- changeset codex:049-create-app-feature-daily-usage
CREATE TABLE IF NOT EXISTS "app_feature_daily_usage" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "feature_key" VARCHAR(64) NOT NULL,
    "feature_name" VARCHAR(120) NOT NULL,
    "activity_date" DATE NOT NULL,
    "first_viewed_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_viewed_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "view_count" BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT "fk_app_feature_daily_usage_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE,
    CONSTRAINT "uk_app_feature_daily_usage_user_feature_date" UNIQUE ("user_id", "feature_key", "activity_date")
);

-- changeset codex:049-index-app-feature-daily-usage-date
CREATE INDEX IF NOT EXISTS "idx_app_feature_daily_usage_date"
    ON "app_feature_daily_usage" ("activity_date");

-- changeset codex:049-index-app-feature-daily-usage-feature-date
CREATE INDEX IF NOT EXISTS "idx_app_feature_daily_usage_feature_date"
    ON "app_feature_daily_usage" ("feature_key", "activity_date");
